### ISSUE TITLE
请教下作者关于bias的设置问题

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#100]
源码如下：
##################################################
bias_cls = -4.595  # 用0.01的置信度初始化
for i in range(len(self.anchor_strides)):
    normal_init(self.gfl_cls[i], std=0.01, bias=bias_cls)
    normal_init(self.gfl_reg[i], std=0.01)
##################################################
1. 这个bias_cls是怎么确定的（如何根据实际去调整这个值） 我个人理解哈，是不是为了让模型输出一开始就能拟合大部分负样本，使得损失集中在正样本身上
2. 为什么只有cls分支要设置bias, reg分支没有
3. 如果bias只应用于cls分支，那么 share_cls_reg == True 的时候，bias也会作用于reg

这个值 会对qfl损失结果产生很大的影响（不清楚为什么box和dfl的损失不受影响），所以感觉是个很重要的设置，还请解惑下，感谢😊

**Comment by RangiLyu** [comment]
bias_cls = -4.595 # 用0.01的置信度初始化
指-4.595经过sigmoid激活函数之后得到的分类置信度为0.01，用这个值初始化可以减小初始的focal loss值，因为模型会在初始化时将大部分结果预测为背景。对使用giou loss的box回归影响不大。
