### ISSUE TITLE
模型后处理好像有个bug，麻烦看下是不是问题

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#102]
在函数
def multiclass_nms
中，过滤score的方法
valid_mask = scores > score_thr
这种过滤方式，会让一个anchor保留多个满足阈值的类别预测，并且共享一个box预测结果
比如有如下过滤结果
anchor_序号1 -- 类别2 -- box[2,3,1,4]
anchor_序号1 -- 类别6 -- box[2,3,1,4]
anchor_序号2 -- 类别2 -- box[1,2,2,2]
...
这些即使经过nms后仍然可能得以保留
就会有问题，打个比方，一辆轿车，相同的box，既会预测为轿车，也会预测为越野
带来了大量的误检

**Comment by RangiLyu** [comment]
分类的label并没有定义为onehot型，用的激活函数也是sigmoid而非softmax，意味着feature map wh维度上同一个点是可以对应多个标签的。
如果你的需求是同一个点只能对应一类目标，那可以在多分类输出取max，只保留置信度最高的类别。

**Comment by connorchen** [comment]
感谢回复
