### ISSUE TITLE
fps值和公布的结果不一致？？？

### ISSUE THREAD

**Issue by lDarryll** [RangiLyu/nanodet#103]
测试数据：coco val2017（5000张图片）
使用的模型：NanoDet-m（作者与训练好的模型）
设备：Jetson AGX Xavier
测试结果： 
       第一次测试：总耗时：329.866s    fps=15.184
       第二次测试：总耗时：336.746s    fps=14.858
测试时间的部分代码：

    begin_time = time.time()     《----------------------开始计时
    if args.demo == 'image':
        if os.path.isdir(args.path):
            files = get_image_list(args.path)
        else:
            files = [args.path]
        files.sort()

        for image_name in files:
            save_result_path = str(Path('/home/user/PycharmProjects/nano/results') / Path(image_name).name)
            meta, res = predictor.inference(image_name)

            predictor.visualize(save_result_path,res, meta, cfg.class_names, 0.35)

            ch = cv2.waitKey(1)
            if ch == 27 or ch == ord('q') or ch == ord('Q'):
                break

    elif args.demo == 'video' or args.demo == 'webcam':
        cap = cv2.VideoCapture(args.path if args.demo == 'video' else args.camid)
        while True:
            ret_val, frame = cap.read()
            meta, res = predictor.inference(frame)
            predictor.visualize(res, meta, cfg.class_names, 0.35)
            ch = cv2.waitKey(1)
            if ch == 27 or ch == ord('q') or ch == ord('Q'):
                break
    print('Done. (%.3fs)' % (time.time() - begin_time))      《---------------------------计算耗时

请问作者您的计算时间的方式是怎样
1. forward  time  ？
2. forward + decode    time  ？
3. forward + decode + vis time ？

希望作者您解除一下我的疑惑， 万分感谢！

**Comment by RangiLyu** [comment]
按照 https://github.com/RangiLyu/nanodet/tree/main/demo_ncnn 的readme运行Benchmark计算时间。
