### ISSUE TITLE
请教下regmax这个值具体是怎么的来的

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#107]
我看到FCOS中regmax=16，而nanodet中regmax=7，这个值和输入图像的大小有关么，具体是怎么换算过来的，希望能够得到您的解惑，谢谢

**Comment by RangiLyu** [comment]
regmax理论上只要大于fpn输出的最小特征图边长的1/2就可以保证预测到的最大的box能够覆盖全图，但由于实际情况下cls分支得到的正样本点不一定位于正中心，因此regmax要略大于1/2的最小特征图边长。320输入下最小特征图边长的1/2为5，因此最终选择了比5略大的7。

**Comment by connorchen** [comment]
多谢，明白了，不过这个值要是通过统计distance获取会更有说服力

**Comment by wwdok** [comment]
@RangiLyu 我注意到repvgg和efficientnet-lite的416版本的config yml里的reg_max
都改成10了，而nanodet-m-416的conofig yml里的reg_max还是7，是疏忽了还是有意保持呢？
