### ISSUE TITLE
您好检测出 mnn 检测出好好多检测框

### ISSUE THREAD

**Issue by xm0629** [RangiLyu/nanodet#108]

**Comment by RangiLyu** [comment]
#92 用1.0.0不要用1.1.0

**Comment by eeric** [comment]
test myself, 
nanodet model convert to MNN one by 1.0.0, not use 1.1.0 or 1.1.2
notice: model converted by MNN-1.0.0 that was use to vs2017 demo_mnn with MNN-1.1.2 library
