### ISSUE TITLE
pth转onnx转ncnn问题

### ISSUE THREAD

**Issue by yhl41001** [RangiLyu/nanodet#110]
您好，我想问一下，我这边用pytorch模型转onnx再转ncnn模型，最后用ncnn模型检测结果不对。
有几个修改：
将config中的val输入改为64x64，将tools/export.py的输入大小改为64x64
python tools/export.py
python -m onnxsim output.onnx output-sim.onnx
build/tools/onnx/onnx2ncnn output-sim.onnx output-sim.param output-sim.bin
build/tools/ncnnoptimize output-sim.param output-sim.bin new-output-sim.param new-output-sim.bin 0
这样操作是这样的
pytorch用的1.7.1
onnx                   1.8.0
onnx-simplifier        0.2.19
onnxoptimizer          0.1.1
onnxruntime            1.6.0

是哪里操作有问题吗？

**Comment by RangiLyu** [comment]
c++代码里的input_size也要对应修改

**Comment by yhl41001** [comment]
c++代码已经修改了，我看了一下我转出来的param文件，和你之前提供的param文件有差异，最开始我的没有输入大小，看起来好像是转onnx或者onnx转ncnn哪里有问题。
这个是我的：
  1 7767517
  2 153 178
  3 Input                    input.1                  0 1 input.1
  4 Convolution              Conv_0                   1 1 input.1 424 0=24 1=3 3=2 4=1 5=1 6=648 9=2 -23310=1,1.000000e-01
  5 Pooling                  MaxPool_2                1 1 424 425 1=3 2=2 3=1 5=1
  6 Split                    splitncnn_0              1 2 425 425_splitncnn_0 425_splitncnn_1
  7 ConvolutionDepthWise     Conv_3                   1 1 425_splitncnn_1 843 0=24 1=3 3=2 4=1 5=1 6=216 7=24
  8 Convolution              Conv_4                   1 1 843 430 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01
  9 Convolution              Conv_6                   1 1 425_splitncnn_0 433 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01
这个是你原来提供的：
7767517
153 178
Input                    input.1                  0 1 input.1 -23330=4,3,320,320,3 0=320 1=320 2=3
Convolution              Conv_0                   1 1 input.1 424 -23330=4,3,160,160,24 0=24 1=3 3=2 4=1 5=1 6=648 9=2 -23310=1,1.000000e-01
Pooling                  MaxPool_3                1 1 424 425 -23330=4,3,80,80,24 1=3 2=2 3=1 5=1
Split                    splitncnn_0              1 2 425 425_splitncnn_0 425_splitncnn_1 -23330=8,3,80,80,24,3,80,80,24
ConvolutionDepthWise     Conv_4                   1 1 425_splitncnn_1 427 -23330=4,3,40,40,24 0=24 1=3 3=2 4=1 5=1 6=216 7=24
Convolution              Conv_6                   1 1 427 430 -23330=4,3,40,40,58 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01
Convolution              Conv_9                   1 1 425_splitncnn_0 433 -23330=4,3,80,80,58 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01

您方便加一下qq或者微信吗？

**Comment by RangiLyu** [comment]
ncnn param里的输入大小只用于shape_inference和madd计算，不影响使用

**Comment by yhl41001** [comment]
我转的onnx输入输入如下：
format
ONNX v6
producer
pytorch 1.7
imports
ai.onnx v11
input.1
name: input.1
type: float32[1,3,64,64]
792
name: 792
type: float32[1,64,80]
814
name: 814
type: float32[1,16,80]
836
name: 836
type: float32[1,4,80]
795
name: 795
type: float32[1,64,32]
817
name: 817
type: float32[1,16,32]
839
name: 839
type: float32[1,4,32]
输出维度是否有问题，另外您可以把onnx也上传一下吗，我试一下您转的onnx。
还有就是resize在onnx的结构中大小是动态不可见的，这个地方是不是有问题？

**Comment by yhl41001** [comment]
已经解决了，多谢啦！

**Comment by sadicLiu** [comment]
> 已经解决了，多谢啦！

请问咋解决的, 按照readme里的步骤把模型转成ncnn格式, .param和作者提供的有差异, 检测结果也对不齐
