### ISSUE TITLE
how to run in it on compute module3 CPU(similar to raspberripi 3 b+) 1gb ram , 8gb flash memory device

### ISSUE THREAD

**Issue by siva-wellnesys** [RangiLyu/nanodet#111]
hi , i am thinking to run in it on cm3 device, but i am unable to run it. its giving PyTorch dependency error. can you help me for that how to run it on that device.

**Comment by RangiLyu** [comment]
Not recommend using PyTorch on an edge device. Try to run ncnn demo instead.
