### ISSUE TITLE
您好, 在使用 MNN 運行 C++ 版本時, 遇到 Resize error for ConvertTensor14, code=3

### ISSUE THREAD

**Issue by dddd247** [RangiLyu/nanodet#115]
Python 版本的demo_mnn, 可以順利運行.
但照著 demo_mnn 的 C++ 步驟運行後,
遇到了以下問題:
![MNN_problem](https://user-images.githubusercontent.com/13269746/104409529-6e168f80-55a1-11eb-87cb-8c10953117a2.png)
請問有辦法解決嗎?

**Comment by dddd247** [comment]
問題解決了, 主要是 MNN 版本問題, 感謝！

**Comment by RangiLyu** [comment]
#92 MNN version problem

**Comment by eeric** [comment]
test myself,
nanodet model convert to MNN one by 1.0.0, not use 1.1.0 or 1.1.2
notice: model converted by MNN-1.0.0 that was use to vs2017 demo_mnn with MNN-1.1.2 library
