### ISSUE TITLE
No result while using single-class nano model in ncnn

### ISSUE THREAD

**Issue by Sean-hku** [RangiLyu/nanodet#118]
**Hi,我训练了一个person类的nanodet模型，然后通过tool/export.py转为onnx，然后转为ncnn的model，但是发现ncnn的model没有输出，我更改了cpp代码中的类别与图片size，不知道是在转换onnx时候出错还是onnx->NCNN时候出错了。下面是我训练时候的cfg**
```bash
#Config File example
save_dir: workspace/nanodet_m
model:
  arch:
    name: GFL
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: ../data/yoga_coco/images/train2017
    ann_path: ../data/yoga_coco/annotations/instances_train2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: coco
    img_path: ../data/yoga_coco/images/val2017
    ann_path: ../data/yoga_coco/annotations/instances_val2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 6
  batchsize_per_gpu: 40
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 50
  lr_schedule:
    name: MultiStepLR
    milestones: [130,160,175,185]
    gamma: 0.1
  val_intervals: 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['person',]
```
**当我使用80类的model时，转化为ncnn有结果，所以想问问 当转化成single-class时候，有什么配置是需要再修改一下的。**

**Comment by Sean-hku** [comment]
**This is my nanodet_m.param file**

7767517
153 178
Input                    input.1                  0 1 input.1
Convolution              Conv_0                   1 1 input.1 424 0=24 1=3 3=2 4=1 5=1 6=648 9=2 -23310=1,1.000000e-01
Pooling                  MaxPool_3                1 1 424 425 1=3 2=2 3=1 5=1
Split                    splitncnn_0              1 2 425 425_splitncnn_0 425_splitncnn_1
ConvolutionDepthWise     Conv_4                   1 1 425_splitncnn_1 426 0=24 1=3 3=2 4=1 5=1 6=216 7=24
Convolution              Conv_6                   1 1 426 430 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01
Convolution              Conv_9                   1 1 425_splitncnn_0 433 0=58 1=1 5=1 6=1392 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_12                  1 1 433 434 0=58 1=3 3=2 4=1 5=1 6=522 7=58
Convolution              Conv_14                  1 1 434 438 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
Concat                   Concat_17                2 1 430 438 439
ShuffleChannel           Reshape_22               1 1 439 444 0=2
Slice                    Split_23                 1 2 444 445 446 -23300=2,58,-233
Convolution              Conv_24                  1 1 446 449 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_27                  1 1 449 450 0=58 1=3 4=1 5=1 6=522 7=58
Convolution              Conv_29                  1 1 450 454 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
Concat                   Concat_32                2 1 445 454 455
ShuffleChannel           Reshape_37               1 1 455 460 0=2
Slice                    Split_38                 1 2 460 461 462 -23300=2,58,-233
Convolution              Conv_39                  1 1 462 465 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_42                  1 1 465 466 0=58 1=3 4=1 5=1 6=522 7=58
Convolution              Conv_44                  1 1 466 470 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
Concat                   Concat_47                2 1 461 470 471
ShuffleChannel           Reshape_52               1 1 471 476 0=2
Slice                    Split_53                 1 2 476 477 478 -23300=2,58,-233
Convolution              Conv_54                  1 1 478 481 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_57                  1 1 481 482 0=58 1=3 4=1 5=1 6=522 7=58
Convolution              Conv_59                  1 1 482 486 0=58 1=1 5=1 6=3364 9=2 -23310=1,1.000000e-01
Concat                   Concat_62                2 1 477 486 487
ShuffleChannel           Reshape_67               1 1 487 492 0=2
Split                    splitncnn_1              1 3 492 492_splitncnn_0 492_splitncnn_1 492_splitncnn_2
ConvolutionDepthWise     Conv_68                  1 1 492_splitncnn_2 493 0=116 1=3 3=2 4=1 5=1 6=1044 7=116
Convolution              Conv_70                  1 1 493 497 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Convolution              Conv_73                  1 1 492_splitncnn_1 500 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_76                  1 1 500 501 0=116 1=3 3=2 4=1 5=1 6=1044 7=116
Convolution              Conv_78                  1 1 501 505 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_81                2 1 497 505 506
ShuffleChannel           Reshape_86               1 1 506 511 0=2
Slice                    Split_87                 1 2 511 512 513 -23300=2,116,-233
Convolution              Conv_88                  1 1 513 516 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_91                  1 1 516 517 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_93                  1 1 517 521 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_96                2 1 512 521 522
ShuffleChannel           Reshape_101              1 1 522 527 0=2
Slice                    Split_102                1 2 527 528 529 -23300=2,116,-233
Convolution              Conv_103                 1 1 529 532 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_106                 1 1 532 533 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_108                 1 1 533 537 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_111               2 1 528 537 538
ShuffleChannel           Reshape_116              1 1 538 543 0=2
Slice                    Split_117                1 2 543 544 545 -23300=2,116,-233
Convolution              Conv_118                 1 1 545 548 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_121                 1 1 548 549 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_123                 1 1 549 553 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_126               2 1 544 553 554
ShuffleChannel           Reshape_131              1 1 554 559 0=2
Slice                    Split_132                1 2 559 560 561 -23300=2,116,-233
Convolution              Conv_133                 1 1 561 564 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_136                 1 1 564 565 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_138                 1 1 565 569 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_141               2 1 560 569 570
ShuffleChannel           Reshape_146              1 1 570 575 0=2
Slice                    Split_147                1 2 575 576 577 -23300=2,116,-233
Convolution              Conv_148                 1 1 577 580 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_151                 1 1 580 581 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_153                 1 1 581 585 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_156               2 1 576 585 586
ShuffleChannel           Reshape_161              1 1 586 591 0=2
Slice                    Split_162                1 2 591 592 593 -23300=2,116,-233
Convolution              Conv_163                 1 1 593 596 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_166                 1 1 596 597 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_168                 1 1 597 601 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_171               2 1 592 601 602
ShuffleChannel           Reshape_176              1 1 602 607 0=2
Slice                    Split_177                1 2 607 608 609 -23300=2,116,-233
Convolution              Conv_178                 1 1 609 612 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_181                 1 1 612 613 0=116 1=3 4=1 5=1 6=1044 7=116
Convolution              Conv_183                 1 1 613 617 0=116 1=1 5=1 6=13456 9=2 -23310=1,1.000000e-01
Concat                   Concat_186               2 1 608 617 618
ShuffleChannel           Reshape_191              1 1 618 623 0=2
Split                    splitncnn_2              1 3 623 623_splitncnn_0 623_splitncnn_1 623_splitncnn_2
ConvolutionDepthWise     Conv_192                 1 1 623_splitncnn_2 624 0=232 1=3 3=2 4=1 5=1 6=2088 7=232
Convolution              Conv_194                 1 1 624 628 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
Convolution              Conv_197                 1 1 623_splitncnn_1 631 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_200                 1 1 631 632 0=232 1=3 3=2 4=1 5=1 6=2088 7=232
Convolution              Conv_202                 1 1 632 636 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
Concat                   Concat_205               2 1 628 636 637
ShuffleChannel           Reshape_210              1 1 637 642 0=2
Slice                    Split_211                1 2 642 643 644 -23300=2,232,-233
Convolution              Conv_212                 1 1 644 647 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_215                 1 1 647 648 0=232 1=3 4=1 5=1 6=2088 7=232
Convolution              Conv_217                 1 1 648 652 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
Concat                   Concat_220               2 1 643 652 653
ShuffleChannel           Reshape_225              1 1 653 658 0=2
Slice                    Split_226                1 2 658 659 660 -23300=2,232,-233
Convolution              Conv_227                 1 1 660 663 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_230                 1 1 663 664 0=232 1=3 4=1 5=1 6=2088 7=232
Convolution              Conv_232                 1 1 664 668 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
Concat                   Concat_235               2 1 659 668 669
ShuffleChannel           Reshape_240              1 1 669 674 0=2
Slice                    Split_241                1 2 674 675 676 -23300=2,232,-233
Convolution              Conv_242                 1 1 676 679 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_245                 1 1 679 680 0=232 1=3 4=1 5=1 6=2088 7=232
Convolution              Conv_247                 1 1 680 684 0=232 1=1 5=1 6=53824 9=2 -23310=1,1.000000e-01
Concat                   Concat_250               2 1 675 684 685
ShuffleChannel           Reshape_255              1 1 685 690 0=2
Convolution              Conv_256                 1 1 492_splitncnn_0 691 0=96 1=1 5=1 6=11136
Convolution              Conv_257                 1 1 623_splitncnn_0 692 0=96 1=1 5=1 6=22272
Convolution              Conv_258                 1 1 690 693 0=96 1=1 5=1 6=44544
Split                    splitncnn_3              1 2 693 693_splitncnn_0 693_splitncnn_1
Interp                   Resize_277               1 1 693_splitncnn_1 712 0=2 3=26 4=26
BinaryOp                 Add_278                  2 1 692 712 713
Split                    splitncnn_4              1 2 713 713_splitncnn_0 713_splitncnn_1
Interp                   Resize_297               1 1 713_splitncnn_1 732 0=2 3=52 4=52
BinaryOp                 Add_298                  2 1 691 732 733
Split                    splitncnn_5              1 2 733 733_splitncnn_0 733_splitncnn_1
Interp                   Resize_317               1 1 733_splitncnn_1 752 0=2 3=26 4=26
BinaryOp                 Add_318                  2 1 713_splitncnn_0 752 753
Split                    splitncnn_6              1 2 753 753_splitncnn_0 753_splitncnn_1
Interp                   Resize_337               1 1 753_splitncnn_1 772 0=2 3=13 4=13
BinaryOp                 Add_338                  2 1 693_splitncnn_0 772 773
ConvolutionDepthWise     Conv_339                 1 1 733_splitncnn_0 776 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_342                 1 1 776 779 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_345                 1 1 779 782 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_348                 1 1 782 785 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
Convolution              Conv_351                 1 1 785 786 0=33 1=1 5=1 6=3168
Slice                    Split_352                1 2 786 787 788 -23300=2,1,-233
Sigmoid                  Sigmoid_353              1 1 787 789
Reshape                  Reshape_355              1 1 789 791 0=-1 1=1
Permute                  Transpose_356            1 1 791 792 0=1
Reshape                  Reshape_358              1 1 788 794 0=-1 1=32
Permute                  Transpose_359            1 1 794 795 0=1
ConvolutionDepthWise     Conv_360                 1 1 753_splitncnn_0 798 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_363                 1 1 798 801 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_366                 1 1 801 804 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_369                 1 1 804 807 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
Convolution              Conv_372                 1 1 807 808 0=33 1=1 5=1 6=3168
Slice                    Split_373                1 2 808 809 810 -23300=2,1,-233
Sigmoid                  Sigmoid_374              1 1 809 811
Reshape                  Reshape_376              1 1 811 813 0=-1 1=1
Permute                  Transpose_377            1 1 813 814 0=1
Reshape                  Reshape_379              1 1 810 816 0=-1 1=32
Permute                  Transpose_380            1 1 816 817 0=1
ConvolutionDepthWise     Conv_381                 1 1 773 820 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_384                 1 1 820 823 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_387                 1 1 823 826 0=96 1=3 4=1 5=1 6=864 7=96 9=2 -23310=1,1.000000e-01
Convolution              Conv_390                 1 1 826 829 0=96 1=1 5=1 6=9216 9=2 -23310=1,1.000000e-01
Convolution              Conv_393                 1 1 829 830 0=33 1=1 5=1 6=3168
Slice                    Split_394                1 2 830 831 832 -23300=2,1,-233
Sigmoid                  Sigmoid_395              1 1 831 833
Reshape                  Reshape_397              1 1 833 835 0=-1 1=1
Permute                  Transpose_398            1 1 835 836 0=1
Reshape                  Reshape_400              1 1 832 838 0=-1 1=32
Permute                  Transpose_401            1 1 838 839 0=1

**Comment by RangiLyu** [comment]
param文件看上去没有问题。
main.cpp 的resize_uniform输入大小和nanodet.h的labels, input_size, num_class 都修改了吗？

**Comment by Sean-hku** [comment]
嗯嗯 我用的是nihui那边的inference 修改完可以了。谢谢
我想请教两个问题：
1.input size是否一定要和转onnx的时候的input size一致，然而onnx的input size要和训练的input size一致。如下图，
![image](https://user-images.githubusercontent.com/63987404/104977781-51fc6d80-5a3b-11eb-96c2-f4d9f7c89eb6.png)
我在（608,608）下训练的，转onnx和ncnn的inference都应该在608下是嘛
2.因为我的数据集只有一类person，想在coco上做pretrain，不知道是pretrain80类的coco数据集还是pretrain只有一类person的coco数据集好一些。
感谢！！！！

**Comment by Sean-hku** [comment]
> param文件看上去没有问题。
> main.cpp 的resize_uniform输入大小和nanodet.h的labels, input_size, num_class 都修改了吗？
嗯嗯 我用的是nihui那边的inference 修改完可以了。谢谢
我想请教两个问题：
1.input size是否一定要和转onnx的时候的input size一致，然而onnx的input size要和训练的input size一致。如下图，


![](https://user-images.githubusercontent.com/63987404/104977781-51fc6d80-5a3b-11eb-96c2-f4d9f7c89eb6.png)

我在（608,608）下训练的，转onnx和ncnn的inference都应该在608下是嘛
2.因为我的数据集只有一类person，想在coco上做pretrain，不知道是pretrain80类的coco数据集还是pretrain只有一类person的coco数据集好一些。
感谢！！！！

**Comment by RangiLyu** [comment]
1. input size是否一定要和转onnx的时候的input size一致：input size需要和训练时保持一致，如果使用nihui的动态分辨率版本，则需要保持最长边长度和训练时一致
2. 在coco上只用人预训练或者可以把coco的人提取出来和你的数据集混合训练

**Comment by ling9601** [comment]
> 1. input size是否一定要和转onnx的时候的input size一致：input size需要和训练时保持一致，如果使用nihui的动态分辨率版本，则需要保持最长边长度和训练时一致
> 2. 在coco上只用人预训练或者可以把coco的人提取出来和你的数据集混合训练

@RangiLyu 
在coco上只训练人检测，是不是在coco2017上把含人的图片提取出来，进行训练？
