### ISSUE TITLE
使用ncnn推理竟然比demo.py推理精度高

### ISSUE THREAD

**Issue by weilanShi** [RangiLyu/nanodet#119]
非常感谢大佬开源如此优秀的模型，欣喜之余，发现几个难以理解的问题：我在使用ncnn推理时竟然比使用项目下的demo.py推理精度高，同一个模型，这是什么原因啊，大佬能解释下吗

**Comment by weilanShi** [comment]
> 非常感谢大佬开源如此优秀的模型，欣喜之余，发现几个难以理解的问题：我在使用ncnn推理时竟然比使用项目下的demo.py推理精度高，同一个模型，这是什么原因啊，大佬能解释下吗

问题已解决

**Comment by RangiLyu** [comment]
> > 非常感谢大佬开源如此优秀的模型，欣喜之余，发现几个难以理解的问题：我在使用ncnn推理时竟然比使用项目下的demo.py推理精度高，同一个模型，这是什么原因啊，大佬能解释下吗
> 
> 问题已解决

是什么原因导致的呢？

**Comment by Kyrie-Chen** [comment]
你好，请问你在用ncnn推理时的精度和demo.py时推理的精度差别大吗，为什么我在比较时发现两者有一定差距，对比了一下发现误差主要出现在图片resize的时候，你有这个问题吗
