### ISSUE TITLE
Pytoch 1.4 train failed

### ISSUE THREAD

**Issue by Jucjiaswiss** [RangiLyu/nanodet#121]
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)

train on pytoch1.4 training failed！

**Comment by RangiLyu** [comment]
If you got this error when loading the pre-train model, try to download the .pth model for the old version of PyTorch. Otherwise, you can upgrade your PyTorch version to 1.6 or higher.

**Comment by Jucjiaswiss** [comment]
fixed it !thank u!
