### ISSUE TITLE
error when compile the project

### ISSUE THREAD

**Issue by job2003** [RangiLyu/nanodet#122]
生成失败。

“D:\workspace\nanodet\demo_ncnn\build\nanodet_demo.vcxproj”(默认目标) (1) ->
(Link 目标) ->
  ncnn.lib(benchmark.cpp.obj) : fatal error LNK1112: 模块计算机类型“x86”与目标计算机类型“x64”冲突 [D:\workspace\nanodet\demo_ncnn\build\
nanodet_demo.vcxproj]

**Comment by RangiLyu** [comment]
要编译64位的demo就要用64位的ncnn库

**Comment by job2003** [comment]
![image](https://user-images.githubusercontent.com/33893894/105358779-92bdd780-5c31-11eb-8e64-3c4700abde5f.png)

我安装了vs2017，但无法找到Start → Programs → Visual Studio 2017 → Visual Studio Tools → x64 Native Tools Command Prompt for VS 2017。因此使用了x86 Native Tools Command Prompt for VS 2017。
我通过https://blog.csdn.net/sinat_29957455/article/details/105122203这个方法，也没有找到 x64 Native Tools Command Prompt for VS 2017。如何解决呢？

**Comment by job2003** [comment]
我使用x86 Native Tools Command Prompt for VS 2017，应该就编译成了x86的库了

**Comment by RangiLyu** [comment]
”x64 Native Tools Command Prompt for VS 2017“ 中文名是 “适用于VS2017的x64本机工具命令提示”，用这个编译

**Comment by job2003** [comment]
![image](https://user-images.githubusercontent.com/33893894/105508070-e5b58e80-5d06-11eb-91c9-5790b0421dc6.png)

编译时出现以上错误，如何解决。

**Comment by job2003** [comment]
D:\workspace\nanodet\demo_ncnn\build>msbuild nanodet_demo.vcxproj /p:configuration=release /p:platform=x64
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2021/1/22 23:08:40。
节点 1 上的项目“D:\workspace\nanodet\demo_ncnn\build\nanodet_demo.vcxproj”(默认目标)。
项目“D:\workspace\nanodet\demo_ncnn\build\nanodet_demo.vcxproj”(1)正在节点 1 上生成“D:\workspace\nanodet\demo_ncnn\build\ZERO_CH
ECK.vcxproj”(2) (默认目标)。
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(6
5,5): error MSB8020: 无法找到 Visual Studio 2010 的生成工具(平台工具集 =“v100”)。若要使用 v100 生成工具进行生成，请安装 Visual Studio 2010 生成工具。或者，可以升
级到当前 Visual Studio 工具，方式是通过选择“项目”菜单或右键单击该解决方案，然后选择“重定解决方案目标”。 [D:\workspace\nanodet\demo_ncnn\build\ZERO_CHECK.vcxproj]
已完成生成项目“D:\workspace\nanodet\demo_ncnn\build\ZERO_CHECK.vcxproj”(默认目标)的操作 - 失败。

已完成生成项目“D:\workspace\nanodet\demo_ncnn\build\nanodet_demo.vcxproj”(默认目标)的操作 - 失败。


生成失败。

“D:\workspace\nanodet\demo_ncnn\build\nanodet_demo.vcxproj”(默认目标) (1) ->
“D:\workspace\nanodet\demo_ncnn\build\ZERO_CHECK.vcxproj”(默认目标) (2) ->
(PlatformPrepareForBuild 目标) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets
(65,5): error MSB8020: 无法找到 Visual Studio 2010 的生成工具(平台工具集 =“v100”)。若要使用 v100 生成工具进行生成，请安装 Visual Studio 2010 生成工具。或者，可
以升级到当前 Visual Studio 工具，方式是通过选择“项目”菜单或右键单击该解决方案，然后选择“重定解决方案目标”。 [D:\workspace\nanodet\demo_ncnn\build\ZERO_CHECK.vcxpro
j]

    0 个警告
    1 个错误

已用时间 00:00:00.27
