### ISSUE TITLE
RepVGG问题

### ISSUE THREAD

**Issue by yhl41001** [RangiLyu/nanodet#128]
你好，我想问一下，现在RepVGG的网络结构，没有参与训练和预测吧？

**Comment by RangiLyu** [comment]
暂时还未加入RepVGG作为backbone

**Comment by yhl41001** [comment]
好的，谢谢，这个模型看起来效果和部署应该都不错，有准备加进去训练和做预测吗？

**Comment by RangiLyu** [comment]
Support RepVGG backbone in commit 10deeedc56d915495fdd0f5e78fec4c22a6e53e4 . TODO: Support deploy model convert when exporting ONNX in export.py

**Comment by RangiLyu** [comment]
Support deploy model convert in commit cab52e6258412fa6f6e760b84005d7603b2573ab

**Comment by yhl41001** [comment]
好的，非常感谢！我试一下效果。
