### ISSUE TITLE
how to train the custom dataset with nanodet-m network

### ISSUE THREAD

**Issue by siva-wellnesys** [RangiLyu/nanodet#129]
hi i am trying to train the model with nanodet-m network. but model size is still 7MB. can you tell me the which parameters to be changed in the nanodet-m yml file and train.py file?

**Comment by RangiLyu** [comment]
The model size of the .pth file is not equal to the model size. The .pth file is a checkpoint of the training process, which containing an optimizer and other parameters. You can use export.py in tools folder to get a 3.7MB onnx model or use torch.save() without saving the optimizer to get a 3.7MB pth file. Then convert onnx to ncnn and use ncnn-optimize to get a 1.8MB fp-16 model.

**Comment by siva-wellnesys** [comment]
shall the same .onnx model for prediction?
and how can we use the .pth model to run on the mnn_demo.py

**Comment by RangiLyu** [comment]
1. You can use run .onnx file with onnxruntime or opencv.
2. You should use tools/export.py to convert your .pth model to onnx and then convert to mnn model.
