### ISSUE TITLE
训练时出现TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by liuwei3612** [RangiLyu/nanodet#13]
[root][11-25 09:57:37]INFO:Using Tensorboard, logs will be saved in iGuard-v1-images-0-484-coco/logs
[root][11-25 09:57:37]INFO:Creating model...
model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
[root][11-25 09:57:37]INFO:Setting up data...
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 72, in main
    pin_memory=True, collate_fn=collate_function, drop_last=True)
  File "/home/lw/anaconda3/envs/nanodet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/lw/anaconda3/envs/nanodet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/home/lw/anaconda3/envs/nanodet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 102, in num_samples
    return len(self.data_source)
TypeError: object of type 'NoneType' has no len()

大佬帮忙看下

**Comment by RangiLyu** [comment]
确认一下是否正确读取了数据集的annotation和image

**Comment by eeric** [comment]
labels: txt-->xml-->json
This project support to Nanodet project to make official labels.
https://github.com/eeric/yolo2voc2coco

successfully， as following：
[root][12-01 02:42:11]INFO:val|Epoch2/70|Iter123(4940/4952)| lr:1.40e-01| loss_qfl:0.6564| loss_bbox:0.9067| loss_dfl:0.3167| 
[root][12-01 02:42:11]INFO:val|Epoch2/70|Iter123(4942/4952)| lr:1.40e-01| loss_qfl:0.3882| loss_bbox:0.7180| loss_dfl:0.2757| 
[root][12-01 02:42:12]INFO:val|Epoch2/70|Iter123(4944/4952)| lr:1.40e-01| loss_qfl:0.2997| loss_bbox:0.7028| loss_dfl:0.2815| 
[root][12-01 02:42:12]INFO:val|Epoch2/70|Iter123(4946/4952)| lr:1.40e-01| loss_qfl:0.4795| loss_bbox:0.5486| loss_dfl:0.2645| 
[root][12-01 02:42:13]INFO:val|Epoch2/70|Iter123(4948/4952)| lr:1.40e-01| loss_qfl:0.4833| loss_bbox:0.8868| loss_dfl:0.2684| 
[root][12-01 02:42:14]INFO:val|Epoch2/70|Iter123(4950/4952)| lr:1.40e-01| loss_qfl:0.5885| loss_bbox:0.7382| loss_dfl:0.3275| 
Loading and preparing results...
DONE (t=3.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Loading and preparing results...
DONE (t=2.72s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=46.62s).
Accumulating evaluation results...
DONE (t=13.37s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.036
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.074
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.061
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.097
