### ISSUE TITLE
get errors when converting model onnx->ncnn

### ISSUE THREAD

**Issue by szhlei** [RangiLyu/nanodet#133]
I get errors when trying to convert NanoDet pytorch model to ncnn.

Run tools/export.py. Then using onnx-simplifier to simplify onnx structure.

Then got errors when converting onnx model to ncnn:

![image](https://user-images.githubusercontent.com/78141454/106114148-39eac380-618a-11eb-8df5-eb08670f818f.png)
![image](https://user-images.githubusercontent.com/78141454/106114255-50911a80-618a-11eb-9851-cf4ff7acfb0a.png)

**Comment by szhlei** [comment]
Shape not supported yet!
Gather not supported yet!
# axis=0
Shape not supported yet!
Gather not supported yet!
# axis=0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
Shape not supported yet!
Gather not supported yet!
# axis=0
Shape not supported yet!
Gather not supported yet!
# axis=0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
Shape not supported yet!
Gather not supported yet!
# axis=0
Shape not supported yet!
Gather not supported yet!
# axis=0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
Shape not supported yet!
Gather not supported yet!
# axis=0
Shape not supported yet!
Gather not supported yet!
# axis=0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!

**Comment by RangiLyu** [comment]
Try to use onnx-simplifier before converting to ncnn.

**Comment by szhlei** [comment]
yeah，I do use onnx-simplifier, but still get these errors when converting to ncnn.
![image](https://user-images.githubusercontent.com/78141454/106117795-58eb5480-618e-11eb-8dcb-e2e648c2c4f1.png)

**Comment by szhlei** [comment]
By the way, I used the xml-dataset, and has modify parameters like: num_classes, class_names, input_size and dataset path etc.

**Comment by RangiLyu** [comment]
> yeah，I do use onnx-simplifier, but still get these errors when converting to ncnn.
> ![image](https://user-images.githubusercontent.com/78141454/106117795-58eb5480-618e-11eb-8dcb-e2e648c2c4f1.png)

You should check the onnx-simplifier option instead of the onnx-optimizer.

**Comment by Yaifan** [comment]
请问解决了吗？遇见同样的问题了，求教
