### ISSUE TITLE
Anchor free?

### ISSUE THREAD

**Issue by lyyiangang** [RangiLyu/nanodet#134]
Hi, 非常感谢开源代码, 我发现计算loss时还是有一个正方形的anchor box, 那么这份代码应该不算Anchor free的方法吧?

**Comment by RangiLyu** [comment]
Anchor free指box建模方式使用中心点到四边的距离，而非anchor+偏移量。而且之所以在计算loss时所需要的正方形anchor，是因为使用了ATSS的label assign方法，可以去阅读ATSS的论文：Bridging the Gap Between Anchor-based and Anchor-free Detection via Adaptive Training Sample Selection。如果换成其他的label assign方式（如FCOS的label assign），则不需要正方形anchor。

**Comment by lyyiangang** [comment]
> Anchor free指box建模方式使用中心点到四边的距离，而非anchor+偏移量。而且之所以在计算loss时所需要的正方形anchor，是因为使用了ATSS的label assign方法，可以去阅读ATSS的论文：Bridging the Gap Between Anchor-based and Anchor-free Detection via Adaptive Training Sample Selection。如果换成其他的label assign方式（如FCOS的label assign），则不需要正方形anchor。
明白了， 非常感谢
