### ISSUE TITLE
May I ask what operation did you do when you converted NCNN from ONNX? With your ONNX file, what I got by myself was different from what you gave me

### ISSUE THREAD

**Issue by TD-wzw** [RangiLyu/nanodet#137]

**Comment by TD-wzw** [comment]
[ShuffleNetV2-sim.zip](https://github.com/RangiLyu/nanodet/files/5902753/ShuffleNetV2-sim.zip)
This is the weight file from my training，I hope you can convert according to your conversion method, help verify the guess.

**Comment by TD-wzw** [comment]
class_num = 1;label = head

**Comment by TD-wzw** [comment]
请给我一些建议，非常感谢！

**Comment by TD-wzw** [comment]
Please give me some advice. Thank you very much

**Comment by TD-wzw** [comment]
I have checked that the output shape of the file I converted by myself is different from that provided by the author. Why

**Comment by RangiLyu** [comment]
I have tested your model. It works fine. 
![image](https://user-images.githubusercontent.com/12907710/106462375-f5845e00-64d0-11eb-9350-924232da2b3d.png)
Here is the converted ncnn  model.
[ShuffleNetV2-ncnn.zip](https://github.com/RangiLyu/nanodet/files/5904072/ShuffleNetV2-ncnn.zip)

By the way, what's the version of ncnn you using?

**Comment by TD-wzw** [comment]
It's strange that I'm using the latest version. How about you?

**Comment by TD-wzw** [comment]
Thank you very much. Indeed, the version of nCNN is too high, and I used the conversion tool in OnNX Simplifier to make it work. The version of the nCNN conversion tool in OnNX Simplifier is older
