### ISSUE TITLE
flops

### ISSUE THREAD

**Issue by StephanPan** [RangiLyu/nanodet#141]
The flops.py may get the MACs actually, since the flops i get from thop package is 2 times of the result received in the flops.py.

**Comment by RangiLyu** [comment]
You are right. I use https://github.com/sovrasov/flops-counter.pytorch in flops.py and the result is actually MACs refer to this issue https://github.com/sovrasov/flops-counter.pytorch/issues/40.
And the FLOPs of NanoDet in README.md has already been multiplied by 2.

**Comment by qsunyuan** [comment]
Mark
