### ISSUE TITLE
求模型结构图

### ISSUE THREAD

**Issue by hive-cas** [RangiLyu/nanodet#144]
各位大佬，能提供下模型完整的结构图么？对照着看代码比较容易些。我用pth可视化工具总是达不到这个效果
![image](https://user-images.githubusercontent.com/19770926/107135118-fedb5380-6932-11eb-95b9-8a04ea7ac321.png)

**Comment by RangiLyu** [comment]
需要导出为onnx模型，再使用netron可视化

**Comment by a328312879** [comment]
樓上正解

**Comment by hive-cas** [comment]
感谢！
