### ISSUE TITLE
libtorch 問題

### ISSUE THREAD

**Issue by a328312879** [RangiLyu/nanodet#148]
您既然給出了liborch的工程，請問libtorch的模型是如何轉換而來的，貌似工程裏面沒有代碼，用官方的轉換方式總是報錯，可否解答一下？謝謝！！！

**Comment by BaofengZan** [comment]
@RangiLyu @a328312879  请问你解决了么？

**Comment by RangiLyu** [comment]
libtorch demo还没做完，之后会提交readme还有导出工具

**Comment by a328312879** [comment]
@BaofengZan 没有，卡在转模型那。我把model里面的几个模块重写了一下，貌似可以转成功。但是代价很大，基本就是定死的架构，无法通过CFG文件更换模型。实际上转换就是个别特性不支持而已。我觉得这个问题还是作者由上至下的修改比较好。我用的1.5的版本，不知道后面1.6或者1.7官方否有改进。

**Comment by RangiLyu** [comment]
Support exporting torchscript after #211 and commit 1ede3ab
