### ISSUE TITLE
    ncnnConfig.cmake,ncnn-config.cmake not found

### ISSUE THREAD

**Issue by hrishikeshps94** [RangiLyu/nanodet#149]
When trying to build project in demo_ncnn for linux found error  ncnnConfig.cmake,ncnn-config.cmake not found

**Comment by RangiLyu** [comment]
You need to set environment parameter first. Run `export​ ncnn_DIR=<YOUR_NCNN_PATH>/build/install/lib/cmake/ncnn`​ before cmake. Remember to replace <YOUR_NCNN_PATH> to your ncnn folder.

**Comment by hrishikeshps94** [comment]
The issue was not with the path, the install folder was not available in the build folder of ncnn, but the issue was resolved with [make install ] command in build folder. Thank you for the response.
