### ISSUE TITLE
load instances_train2017.json error

### ISSUE THREAD

**Issue by eeric** [RangiLyu/nanodet#15]
AttributeError: 'NoneType' object has no attribute 'shape'

load training data by  coco/annotations/instances_train2017.json, how to load?

**Comment by RangiLyu** [comment]
Make sure your img_path is correct and the folder containing all training images. Also avoid unusual characters in the path.

**Comment by eeric** [comment]
could you provide sample format?

original instances_val2017.json as following:
{"info": {"description": "COCO 2017 Dataset","url": "http://cocodataset.org","version": "1.0","year": 2017,"contributor": "COCO Consortium","date_created": "2017/09/01"},"licenses": [{"url": "http://creativecommons.org/licenses/by-nc-sa/2.0/","id": 1,"name": "Attribution-NonCommercial-ShareAlike License"},{"url": "http://creativecommons.org/licenses/by-nc/2.0/","id": 2,"name": "Attribution-NonCommercial License"},{"url": "http://creativecommons.org/licenses/by-nc-nd/2.0/","id": 3,"name": "Attribution-NonCommercial-NoDerivs License"},{"url": "http://creativecommons.org/licenses/by/2.0/","id": 4,"name": "Attribution License"},{"url": "http://creativecommons.org/licenses/by-sa/2.0/","id": 5,"name": "Attribution-ShareAlike License"},{"url": "http://creativecommons.org/licenses/by-nd/2.0/","id": 6,"name": "Attribution-NoDerivs License"},{"url": "http://flickr.com/commons/usage/","id": 7,"name": "No known copyright restrictions"},{"url": "

"area": 10359.753850000001,"iscrowd": 0,"image_id": 494869,"bbox": [197.42,321.09,91.36,198.79],"category_id": 1,"id": 2153738},{"segmentation": [[443.64,207.7,454.51,210.29,453.77,204.9,452.51,201.42,451.55,196.25,451.7,191.44,448.6,187.01,445.49,185.31,443.05,184.72,442.17,186.05,441.58,191.22,441.8,196.76,442.46,198.98,443.79,202.68,444.01,206.15]],"area": 217.7286999999999,"iscrowd": 0,"image_id": 248334,"bbox": [441.58,184.72,12.93,25.57],"category_id": 1,"id": 2154032},{"segmentation": [[285.74,322.35,278.61,322.35,260.29,335.58,262.32,377.32,279.63,403.78,299.99,427.0,348.85,427.0,365.13,427.0,332.56,392.59,439.44,412.95,494.41,414.98,523.93,380.37,516.81,362.05,495.26,339.64,507.32,333.61,549.56,334.47,553.87,305.16,529.74,252.29,509.91,213.5,505.6,195.4,495.26,176.44,476.3,158.34,480.61,127.88,467.68,100.3,434.92,87.37,409.93,98.58,388.38,132.19,390.97,155.46,398.72,170.12,408.2,189.08,419.41,203.73,436.65,208.91,425.44,254.59,422.86,283.9,431.48,289.07,432.34,295.11,421.13,302.86,403.89,309.76,395.27,313.21,404.76,335.62,402.17,347.68,391.83,348.54,305.63,346.82,291.84,341.65]],

**Comment by eeric** [comment]
could your training data format as like yolov5 training data format
https://github.com/ultralytics/yolov5 ?

**Comment by RangiLyu** [comment]
> could your training data format as like yolov5 training data format
> https://github.com/ultralytics/yolov5 ?

Sorry, nanodet currently only support COCO format annotation. You may try to convert yolo format dataset to voc. Then use voc2coco to get a COCO json annotation.

https://github.com/hai-h-nguyen/Yolo2Pascal-annotation-conversion

https://github.com/yukkyo/voc2coco

**Comment by eeric** [comment]
@RangiLyu thank you very much!
