### ISSUE TITLE
如何根本解决anchor冲突的问题

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#157]
抱歉又来打扰了，请教一个问题 ^V^
        训练集难免存在 GT 重叠的问题，之前不管是FCOS还是ATSS都是通过 尺度差异将重叠的 GT 分流到各个 SIZE 的 feature map 上去，减少了大量 anchor 冲突的情况。
        但是一些训练集 分了 自行车，骑行人 和 骑行人整体，这三个不同类别是高度重叠的，我发现在这种训练集上，nanodet的表现不是很好，因为即使是ATSS也没办法解决这种高度重叠的GT带来的anchor冲突问题。
        于是我就想当然的把 box_pred 的输出 乘以 ClsNum（类别的数量） 进行扩展，同时为了简便，舍弃掉 DFL，于是边框回归的输出 从 W x H x 4 --> W x H x 4 x ClsNum。相当于扩展了一个类别维度，这个时候如果anchor存在冲突，同一类别的仍然用 maxIOU 来解决冲突，不同类别的通过分散到各自的类别维度得以解决。
        我说的可能有点乱 -_-!，通过一顿修改，能够进行训练了，不过 box_loss 却不能收敛，不知道您有没有进行过类似的尝试，或者我这样改是否存在什么问题。

**Comment by connorchen** [comment]
刚刚起标题，忘了贴内容了 - -！，我顶一下哈

**Comment by RangiLyu** [comment]
这样做理论上肯定是可行的，只要box head输出的tensor是[batch size, 4xnum_classes, h, w]这样的形状，每4个channel分配给不同的类别就行。不收敛有可能是代码实现上的问题。

**Comment by connorchen** [comment]
感谢回复，我再看下代码

**Comment by lyyiangang** [comment]
@connorchen 同样的问题，请问后来发现是什么原因了么？
