### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by mytk2012** [RangiLyu/nanodet#16]
Build command failed
Error while executing process /home/c/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/c/projects/nandet/nandet-main/demo_android_ncnn/app/.cxx/cmake/debug/armeabi-v7a yolov5}
ninja:Entering directory '/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/.cxx/cmake/debug/armeabi-v7a 
**ninja:error**:'/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/src/main/cpp/ncnnvulkan/armeabi-v7a/libncnn.a',**needed by** '/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/build/intermediates/cmake/debug/obg/armeabi-v7a/libyolov5.so',**missing and no known rules to make it**

**Comment by mytk2012** [comment]
Abosolute path,and i have **checked file libyolov5.so** in /home/c/projects/nandet/nandet-main/demo_android_ncnn/app/build/intermediates/cmake/debug/obg/armeabi-v7a,it was missing,so which settings should i have mistaken

**Comment by mytk2012** [comment]
Abosolute path,and i have **checked file libyolov5.so** in /home/c/projects/nandet/nandet-main/demo_android_ncnn/app/build/intermediates/cmake/debug/obg/armeabi-v7a**,it was missing,**so which **settings** should i have mistaken

**Comment by mytk2012** [comment]
Abosolute path,and i have **checked file libyolov5.so** in /home/c/projects/nandet/nandet-main/demo_android_ncnn/app/build/intermediates/cmake/debug/obg/armeabi-v7a,**it was missing**,so which settings should i have mistaken

**Comment by yurensmile** [comment]
Please make sure you have the right directory name "ncnnvulkan".

**Comment by RangiLyu** [comment]
> Build command failed
> Error while executing process /home/c/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/c/projects/nandet/nandet-main/demo_android_ncnn/app/.cxx/cmake/debug/armeabi-v7a yolov5}
> ninja:Entering directory '/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/.cxx/cmake/debug/armeabi-v7a
> **ninja:error**:'/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/src/main/cpp/ncnnvulkan/armeabi-v7a/libncnn.a',**needed by** '/home/c/projects/nandet/nandet-main/demo_android_ncnn/app/build/intermediates/cmake/debug/obg/armeabi-v7a/libyolov5.so',**missing and no known rules to make it**


Make sure you have ncnnvulkan library and link it correctly in CMakeLists
