### ISSUE TITLE
ncnn推理和demo.py推理的精度差距

### ISSUE THREAD

**Issue by Kyrie-Chen** [RangiLyu/nanodet#162]
你好，我在用ncnn推理时的精度和demo.py推理时的精度有一定差距，对比了一下发现误差主要出现在图片resize的时候，demo.py中采用cv2.warpPerspective()函数进行矩阵相乘，ncnn中直接进行resize，想请问你那边有这个问题吗？

**Comment by RangiLyu** [comment]
这属于预处理方式不同导致的差异，如果要比较模型的精度损失，一般使用resize过的bmp图片作为输入进行对比。

**Comment by Kyrie-Chen** [comment]
那如果我想将训练得到的参数直接用于ncnn推理，需要修改ncnn的resize方式使两者对应吗？否则，如果参数在demo.py中表现较好，移植到ncnn后岂不是不一定会有同样的结果？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RangiLyu/nanodet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月27日(星期六) 中午12:52
收件人:&nbsp;"RangiLyu/nanodet"<nanodet@noreply.github.com&gt;;
抄送:&nbsp;"陈杨波"<1129813529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RangiLyu/nanodet] ncnn推理和demo.py推理的精度差距 (#162)





 
这属于预处理方式不同导致的差异，如果要比较模型的精度损失，一般使用resize过的bmp图片作为输入进行对比。

**Comment by RangiLyu** [comment]
一般来说，resize + padding 和使用 warpAffine直接resize没有本质区别，只是在插值时选取的点有略微不同

**Comment by Kyrie-Chen** [comment]
因为resize的差别，导致相同图片输入下得到的置信度有一定差别，这个对于整体检测精度会有影响吗



---原始邮件---
发件人: "RangiLyu"<notifications@github.com&gt;
发送时间: 2021年3月1日(周一) 晚上6:46
收件人: "RangiLyu/nanodet"<nanodet@noreply.github.com&gt;;
抄送: "Kyrie-Chen"<1129813529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [RangiLyu/nanodet] ncnn推理和demo.py推理的精度差距 (#162)




 
一般来说，resize + padding 和使用 warpAffine直接resize没有本质区别，只是在插值时选取的点有略微不同

**Comment by dingweichao123** [comment]
C++的后处理中fast_exp这个函数结果有些问题，使用cmath自带的exp和Python的推理结果就基本一致了
