### ISSUE TITLE
python demo_mnn.py  initMNN: init numpy failed

### ISSUE THREAD

**Issue by wataincdx** [RangiLyu/nanodet#163]
Traceback (most recent call last):
  File "demo_mnn.py", line 406, in <module>
    class NanoDetMNN(NanoDetABC):
  File "demo_mnn.py", line 407, in NanoDetMNN
    import MNN as MNNlib
  File "C:\5tools\anaconda3\envs\pytorch\lib\site-packages\MNN\__init__.py", line 8, in <module>
    from _mnncengine import *
Exception: initMNN: init numpy failed

**Comment by RangiLyu** [comment]
Have you installed numpy?

**Comment by JackLin-Authme** [comment]
I got same error. I solved it by upgrading numpy to 1.20.x

**Comment by dupeljan** [comment]
Got the same issue with MMN==1.1.4, `pip install MNN==1.1.0` solved the problem

**Comment by freehawkzk** [comment]
I got the same error as MNN==1.1.4, either numpy== 1.19.5 or 1.16.x, 
when i reinstall numpy==1.20, the error was gone.
