### ISSUE TITLE
Bug report for build demo_ncnn on Raspberry Pi

### ISSUE THREAD

**Issue by kevinchan04** [RangiLyu/nanodet#164]
While make the demo_ncnn project on Raspberry pi, I think you have to modify two lines, otherwise you will encounter error while compiling and making the project.

The first one is in [nanodet.cpp](https://github.com/RangiLyu/nanodet/blob/e3acd49dbec58a15ab5bd5d8ba3d6bc96c54145c/demo_ncnn/nanodet.cpp#L50). Comment the line 50 since the raspberry pi without GPU.

```
// this->hasGPU = ncnn::get_gpu_count() > 0;
```

If not, the error is:

> Scanning dependencies of target nanodet_demo
[ 33%] Building CXX object CMakeFiles/nanodet_demo.dir/main.cpp.o
In file included from /home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:6:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
[ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/nanodet.cpp.o
In file included from /home/pi/xiaodong/nanodet/demo_ncnn/nanodet.cpp:6:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.cpp: In constructor ‘NanoDet::NanoDet(const char*, const char*, bool)’:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.cpp:50:26: error: ‘get_gpu_count’ is not a member of ‘ncnn’
     this->hasGPU = ncnn::get_gpu_count() > 0;
                          ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/nanodet_demo.dir/build.make:76: CMakeFiles/nanodet_demo.dir/nanodet.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/nanodet_demo.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

The second one is in [main.cpp](https://github.com/RangiLyu/nanodet/blob/e3acd49dbec58a15ab5bd5d8ba3d6bc96c54145c/demo_ncnn/main.cpp#L229). Modify the line 229 as following.

```
std::vector<cv::String> filenames;
```

if not, the error is;

> [ 33%] Building CXX object CMakeFiles/nanodet_demo.dir/main.cpp.o
In file included from /home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:6:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
/home/pi/xiaodong/nanodet/demo_ncnn/main.cpp: In function ‘int image_demo(NanoDet&, const char*)’:
/home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:230:25: error: invalid initialization of reference of type ‘std::vector<cv::String>&’ from expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
     cv::glob(imagepath, filenames, false);
                         ^~~~~~~~~
In file included from /usr/include/opencv2/core.hpp:3216,
                 from /usr/include/opencv2/core/core.hpp:48,
                 from /home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:1:
/usr/include/opencv2/core/utility.hpp:188:17: note: in passing argument 2 of ‘void cv::glob(cv::String, std::vector<cv::String>&, bool)’
 CV_EXPORTS void glob(String pattern, std::vector<String>& result, bool recursive = false);
                 ^~~~
make[2]: *** [CMakeFiles/nanodet_demo.dir/build.make:63: CMakeFiles/nanodet_demo.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/nanodet_demo.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

>

**Comment by RangiLyu** [comment]
The first issue about gpu has been fixed by PR #168 and #169.

**Comment by sharoseali** [comment]
@kevinchan04 Can you please share the performanbce of nanoDet model ın raspberry Pi lıke FPS or model latency Thanks

**Comment by sharoseali** [comment]
@RangiLyu I tried nanodetect with ncnn library on Rasberry PI 4. I trained the NanoDet-m-416 with one class but the FPS are even less then 1: Any help why the model is so slow? 

> ~/ncnn/nanodet/demo_ncnn/build $ ./nanodet_demo 2 ../test.mp4
> Detect Time: 694.48 
> Detect Time: 708.53 
> Detect Time: 720.38 
> Detect Time: 689.98 
> Detect Time: 692.19 
> Detect Time: 703.93 
> Detect Time: 696.35 
> Detect Time: 691.94 
> Detect Time: 688.03 
> Detect Time: 698.62 
> Detect Time: 693.71 
> Detect Time: 694.72 
> Detect Time: 699.92 
> Detect Time: 686.56 
> Detect Time: 693.09 
> Detect Time: 691.48 
> Detect Time: 693.44 
> Detect Time: 688.60 
> Detect Time: 675.05 
> Detect Time: 675.33 
> Detect Time: 683.85 
> Detect Time: 681.69 
> Detect Time: 678.10 
> Detect Time: 679.07 
> Detect Time: 690.57 
> Detect Time: 684.96 
> Detect Time: 676.87 
> Detect Time: 683.41 
> Detect Time: 669.01 
> Detect Time: 675.45 
> Detect Time: 669.33 
> Detect Time: 667.83
