### ISSUE TITLE
请问可以训练输入为320*240的模型吗？尝试训练的320*240的模型，得到的结果是错乱的

### ISSUE THREAD

**Issue by xxy90** [RangiLyu/nanodet#166]

**Comment by RangiLyu** [comment]
能提供更多的信息吗？比如错误的结果是什么样的？训练时用的是什么参数？

**Comment by xxy90** [comment]
训练的是手掌与拳头目标检测，训练是用0.5x shuffleNet-backnone,loss收敛很正常，结果是目标检测不到

**Comment by xxy90** [comment]
![Uploading image.png…]()
