### ISSUE TITLE
pth转onnx问题

### ISSUE THREAD

**Issue by 205418367** [RangiLyu/nanodet#170]
我先手动下载了pth模型，然后再把pth模型转成onnx模型时又会自动下载pth模型，是什么原因？

**Comment by RangiLyu** [comment]
> 我先手动下载了pth模型，然后再把pth模型转成onnx模型时又会自动下载pth模型，是什么原因？

下载的是训练时用于初始化backbone的imagenet预训练权重，如果想跳过这一步骤可以在配置文件的backbone部分加入pretrain: False 参数
