### ISSUE TITLE
使用COCO测试集测试报错

### ISSUE THREAD

**Issue by JJAndy** [RangiLyu/nanodet#177]
我使用COCO的测试集进行测试，然后报错了。
测试集图片 coco/test2017
测试集label  coco/annotations/image_info_test2017.json(另外还有一个文件叫image_info_testdev2017.json，不知道这两个文件有啥区别，都试了，还是报错了)
测试命令  python tools/test.py config/nanodet-m.yml --task test 选择test 生成的json文件没有测试结果
选择val  会报错
eval_results =  evaluator.evaluate(results, cfg.save_dir, 0, logger, rank=local_rank)
coco_dets =  self.coco_api.loadRes(json_path)
if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by RangiLyu** [comment]
已修复
