### ISSUE TITLE
行人一类 误报率高，请教下怎么修改Nanodet来缓解

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#178]
我在自己的数据上测下来 行人一类 的误报率很高，因为模型改的少，尚不清楚如何修改Nanodet来解决 误报率高的问题。请教下，是修改backbone、还是添加什么损失函数呢，哪些措施对降低误报率有效。期待您的解惑，^v^

另外，我用的nanodet源码比较老了，是刚支持多GPU训练的那一版

**Comment by connorchen** [comment]
这个是我的验证结果，取score大于0.1的预测框：

class [pedestrian] ground truth:[45245] pred num:[337500]
…………(隐去误报成其他类别的比率)
fp_cls background, num 268842, 79.7%

gtBox一共45245个 predBox一共 337500个，落在背景上的predBox有268842个
即使调大阈值仍然会有很多的误检框，最终为了保证precision，recall 比另外一个模型低了几个点

**Comment by betterhalfwzm** [comment]
> 这个是我的验证结果，取score大于0.1的预测框：
> 
> class [pedestrian] ground truth:[45245] pred num:[337500]
> …………(隐去误报成其他类别的比率)
> fp_cls background, num 268842, 79.7%
> 
> gtBox一共45245个 predBox一共 337500个，落在背景上的predBox有268842个
> 即使调大阈值仍然会有很多的误检框，最终为了保证precision，recall 比另外一个模型低了几个点
> 
> loss的配置我用的是默认值
> loss:
> loss_qfl:
> name: QualityFocalLoss
> use_sigmoid: True
> beta: 2.0
> loss_weight: 1.0
> loss_bbox:
> name: GIoULoss
> loss_weight: 2.0
> 
> 理论上，qfl已经在约束类别判断了，是不是要加大qfl的权重呢

请教如何解决的啊

**Comment by connorchen** [comment]
> > 这个是我的验证结果，取score大于0.1的预测框：
> > class [pedestrian] ground truth:[45245] pred num:[337500]
> > …………(隐去误报成其他类别的比率)
> > fp_cls background, num 268842, 79.7%
> > gtBox一共45245个 predBox一共 337500个，落在背景上的predBox有268842个
> > 即使调大阈值仍然会有很多的误检框，最终为了保证precision，recall 比另外一个模型低了几个点
> > loss的配置我用的是默认值
> > loss:
> > loss_qfl:
> > name: QualityFocalLoss
> > use_sigmoid: True
> > beta: 2.0
> > loss_weight: 1.0
> > loss_bbox:
> > name: GIoULoss
> > loss_weight: 2.0
> > 理论上，qfl已经在约束类别判断了，是不是要加大qfl的权重呢
> 
> 请教如何解决的啊

这个问题我还没解决哈

**Comment by betterhalfwzm** [comment]
> > > 这个是我的验证结果，取score大于0.1的预测框：
> > > class [pedestrian] ground truth:[45245] pred num:[337500]
> > > …………(隐去误报成其他类别的比率)
> > > fp_cls background, num 268842, 79.7%
> > > gtBox一共45245个 predBox一共 337500个，落在背景上的predBox有268842个
> > > 即使调大阈值仍然会有很多的误检框，最终为了保证precision，recall 比另外一个模型低了几个点
> > > loss的配置我用的是默认值
> > > loss:
> > > loss_qfl:
> > > name: QualityFocalLoss
> > > use_sigmoid: True
> > > beta: 2.0
> > > loss_weight: 1.0
> > > loss_bbox:
> > > name: GIoULoss
> > > loss_weight: 2.0
> > > 理论上，qfl已经在约束类别判断了，是不是要加大qfl的权重呢
> > 
> > 
> > 请教如何解决的啊
> 
> 这个问题我还没解决哈

好的，谢谢

**Comment by connorchen** [comment]
因为我想先自己动手做些实验来解决这个问题，不过都失败了，总体上没有达到满意的去误报的效果。我觉得误报高主要是两个因素导致的
1、类别-置信度 的联合表示 的监督信息 是 predBox和GT 的IOU，他的范围在0~1，不可避免的背景也会贡献出0.x这样的预测值，大概率使得部分TP的预测框和背景混淆
2、虽然 类别-置信度 的联合表示在表征类别概率的同时，也提供了置信度得分，就像第一条说的，这里置信度得分很难明显隔离正负样本，不像YOLO那样，有个专门的objness的判断节点，它的监督信息是0或1
所以，至少在我的数据及上，nanodet的误报率是个严重的问题，不过它的检出率确实高于我之前试过的模型，不过误报率很高很可惜，希望nanodet的后续更新能专门解决下我遇到的这类问题。
如果作者能看到这条消息，也希望能给出一些好的办法，我已经黔驴技穷了 -_-!

**Comment by connorchen** [comment]
> > > > 这个是我的验证结果，取score大于0.1的预测框：
> > > > class [pedestrian] ground truth:[45245] pred num:[337500]
> > > > …………(隐去误报成其他类别的比率)
> > > > fp_cls background, num 268842, 79.7%
> > > > gtBox一共45245个 predBox一共 337500个，落在背景上的predBox有268842个
> > > > 即使调大阈值仍然会有很多的误检框，最终为了保证precision，recall 比另外一个模型低了几个点
> > > > loss的配置我用的是默认值
> > > > loss:
> > > > loss_qfl:
> > > > name: QualityFocalLoss
> > > > use_sigmoid: True
> > > > beta: 2.0
> > > > loss_weight: 1.0
> > > > loss_bbox:
> > > > name: GIoULoss
> > > > loss_weight: 2.0
> > > > 理论上，qfl已经在约束类别判断了，是不是要加大qfl的权重呢
> > > 
> > > 
> > > 请教如何解决的啊
> > 
> > 
> > 这个问题我还没解决哈
> 
> 好的，谢谢

不过这样就不是 one-stage了 ~_~

**Comment by www516717402** [comment]
@connorchen 对于简单样本nanodet检测的较好，对于复杂样本很容易误检。个人感觉是anchor分配的问题。
目前解决方案：
- 增加feature层
- 增加负样本
- 多尺度训练
- 修改PAFPN
- 后面加一个分类器（这个方法有点冗余，尝试过误检多的情况下不适用）
最终效果还可以，对于特别复杂的场景误检依旧存在，我还是使用的anchor-base。
[参考](https://www.cnblogs.com/wjy-lulu/p/14124058.html)

**Comment by connorchen** [comment]
> @connorchen 对于简单样本nanodet检测的较好，对于复杂样本很容易误检。个人感觉是anchor分配的问题，如果增加anchor就不是free的做法了。。。
> 目前解决方案：
> 
> * 增加feature层
> * 增加负样本
> * 多尺度训练
> * 修改PAFPN
> * 后面加一个分类器（这个方法有点冗余，尝试过误检多的情况下不适用）
>   最终效果还可以，对于特别复杂的场景误检依旧存在，我还是使用的anchor-base。
>   [参考](https://www.cnblogs.com/wjy-lulu/p/14124058.html)

没什么方向了，不过可以尝试下 抱拳.jpg

**Comment by zhangkui669** [comment]
误检多就针对性的增加一些负样本，这是成本最低且最有效的方法，你得用数据集告诉模型哪些样本是不该检出的

**Comment by zhangkui669** [comment]
另外如果计算资源充足的话，可以适当的增加一个分类器，检出的目标再过一遍分类器，这是业界常用的方法
