### ISSUE TITLE
How to modify the configuration with cpu?

### ISSUE THREAD

**Issue by lanteng77** [RangiLyu/nanodet#18]
I wanna to modify the configuration with cpu？I have no idea.

**Comment by zacario-li** [comment]
@lanteng77 You mean train or test?
If test, modify the line from 'cuda:0' to 'cpu'
[predictor = Predictor(cfg, args.model, logger, device='cuda:0')](https://github.com/RangiLyu/nanodet/blob/5a7a50108d4c6815fc4bbcc382d08c8679143449/demo/demo.py#L80)

**Comment by lanteng77** [comment]
I don't have a GPU, so training needs to be modified.

**Comment by RangiLyu** [comment]
> I don't have a GPU, so training needs to be modified.
Sorry, nanodet current not support cpu training. You can try to change all .to('cuda') to .to('cpu') in this project. But I can't make sure that it will work. Just have a try.

**Comment by zhongguogu** [comment]
```
(nanodet) zhongguo.gu@sh-pip-pdfengine02:/datayes/marchinelearning/nanodet$ python demo/demo.py image --config config/nanodet-m.yml   --model model/nanodet_m.pth  --path input/1.jpg 
model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
[root][11-25 22:09:37]INFO:Press "Esc", "q" or "Q" to exit.
Traceback (most recent call last):
  File "demo/demo.py", line 107, in <module>
    main()
  File "demo/demo.py", line 90, in main
    meta, res = predictor.inference(image_name)
  File "demo/demo.py", line 53, in inference
    results = self.model.inference(meta)
  File "/datayes/marchinelearning/nanodet/nanodet/model/arch/one_stage.py", line 34, in inference
    torch.cuda.synchronize()
  File "/home/zhongguo.gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 378, in synchronize
    _lazy_init()
  File "/home/zhongguo.gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
i have modified   the line from 'cuda:0' to 'cpu'
predictor = Predictor(cfg, args.model, logger, device='cuda:0')  => predictor = Predictor(cfg, args.model, logger, device='cpu'), 
but still throw an exception.

**Comment by RangiLyu** [comment]
> ```
> (nanodet) gu@local:/home/marchinelearning/nanodet$ python demo/demo.py image --config config/nanodet-m.yml   --model model/nanodet_m.pth  --path input/1.jpg 
> model size is  1.0x
> init weights...
> => loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
> Finish initialize Lite GFL Head.
> [root][11-25 22:09:37]INFO:Press "Esc", "q" or "Q" to exit.
> Traceback (most recent call last):
>   File "demo/demo.py", line 107, in <module>
>     main()
>   File "demo/demo.py", line 90, in main
>     meta, res = predictor.inference(image_name)
>   File "demo/demo.py", line 53, in inference
>     results = self.model.inference(meta)
>   File "/home/marchinelearning/nanodet/nanodet/model/arch/one_stage.py", line 34, in inference
>     torch.cuda.synchronize()
>   File "/home/gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 378, in synchronize
>     _lazy_init()
>   File "/home/gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled
> ```
> 
> i have modified the line from 'cuda:0' to 'cpu'
> predictor = Predictor(cfg, args.model, logger, device='cuda:0') => predictor = Predictor(cfg, args.model, logger, device='cpu'),
> but still throw an exception.

Try to comment out all ` torch.cuda.synchronize()`.

**Comment by siva-wellnesys** [comment]
still the issue is same @RangiLyu 
i tried these things
1)Try to comment out all torch.cuda.synchronize()
2)  have modified the line from 'cuda:0' to 'cpu'
3) changed all .to('cuda') to .to('cpu')

still facing this same issue


  File "/home/marchinelearning/nanodet/nanodet/model/arch/one_stage.py", line 34, in inference
    torch.cuda.synchronize()
  File "/home/gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 378, in synchronize
    _lazy_init()
  File "/home/gu/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by wwdok** [comment]
@siva-wellnesys There is still a `torch.cuda.synchronize()` you didn't comment out, this issue should be solved by above discussion.
