### ISSUE TITLE
int8 quantization 

### ISSUE THREAD

**Issue by LoaferCH** [RangiLyu/nanodet#180]
Hello! Thank you for the net, it is really great!
I trained it and achieved good results, however I need to make it faster by converting it to int8.

I am using openvino DL Workbench to do the quantization, but the tool is limited and the result of optimization is a slower model. I am planning to use it in openvino format (xml, bin).

Have you tried converting your model to int8? If yes, please give me an advice on how to do it.

Thank you!

**Comment by RangiLyu** [comment]
Add int8 models in #246. Following this guide to get int8 quantized models https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
