### ISSUE TITLE
How to trace the model for libtorch/torch script

### ISSUE THREAD

**Issue by WarriorMmb** [RangiLyu/nanodet#185]
How to trace the model for libtorch/torch script. Should I use torch.jit.trace or some different thing.

**Comment by henbucuoshanghai** [comment]
me too            help

**Comment by strawberrypie** [comment]
You can use this script: https://github.com/RangiLyu/nanodet/blob/main/tools/export_torchscript.py

**Comment by RangiLyu** [comment]
Support exporting torchscript after #211 and commit 1ede3ab
