### ISSUE TITLE
为什么下载的.pth模型文件默认是用zip打开,torch.load也加载不了

### ISSUE THREAD

**Issue by qinhuaping** [RangiLyu/nanodet#19]
为什么下载的.pth模型文件默认是用zip打开,torch.load也加载不了

**Comment by RangiLyu** [comment]
尝试使用1.6版本或更高版本的pytorch，pytorch更新1.6之后Pth文件格式发生了变更，旧版本的可能不兼容新版本保存的权重了

**Comment by RangiLyu** [comment]
.pth file for older version of pytorch(<1.6) has been uploaded. Download from here:   https://drive.google.com/file/d/10h-0qLMCgYvWQvKULqbkLvmirFR-w9NN/view?usp=sharing

**Comment by qinhuaping** [comment]
thank you very much!!
