### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by batrlatom** [RangiLyu/nanodet#190]
Hi, I am trying to use checkpoint of the already trained model, but getting an error:

```AttributeError: seek. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.```

It happens with every model I am trying to use. It looks like this in the config file:
```
schedule:
  resume:
    load_model: workspace/nanodet_m_416/model_last.pth
```
Is there some easy solution to this?

**Comment by RangiLyu** [comment]
Like this:
```
schedule:
  # resume:
  load_model: workspace/nanodet_m_416/model_last.pth
```
```load_model``` and ```resume``` are two different ways to load model. ```resume``` will automatically load the 'model_last.pth'.  ```load_model``` is for manually setting the path to the .pth file.

**Comment by batrlatom** [comment]
I see, thank you!
