### ISSUE TITLE
只有一类目标时有哪里需要注意吗？

### ISSUE THREAD

**Issue by ForeverPs** [RangiLyu/nanodet#192]
只想检测出bbox，不关注类别信息，于是我将所有的类别标签设置为1，然后在config文件中将num_classes设置为1，结果在训练的过程中loss_qfl，loss_dfl以及loss_bbox都是0
![企业微信截图_20210322171255](https://user-images.githubusercontent.com/47919727/111966430-e06f9700-8b31-11eb-8c86-82030678d179.png)

**Comment by ForeverPs** [comment]
Solved. Something wrong with my attribute super category.

**Comment by sunjunlishi** [comment]
@ForeverPs 多个标签类别训练没问题吧，怎么我感觉测试精度低奥，加上多个标签类别的化？

**Comment by rex-yue-wu** [comment]
@ForeverPs 能具体说说吗？我遇到了同样的问题，但是我的数据集里面压根也没有super category的标注，还是说，需要手动加上一个？
