### ISSUE TITLE
validate metric abnormal

### ISSUE THREAD

**Issue by xiaotown123** [RangiLyu/nanodet#204]
![image](https://user-images.githubusercontent.com/6803181/114043616-067a9280-98b9-11eb-84bc-71c1400b6127.png)

What is the possible problem? data annotation?

**Comment by RangiLyu** [comment]
Usually it's because the dataset and annotation are not correct.

**Comment by xiaotown123** [comment]
> Usually it's because the dataset and annotation are not correct.

OK, Thanks
