### ISSUE TITLE
about model size

### ISSUE THREAD

**Issue by xiaotown123** [RangiLyu/nanodet#209]
I download coco pre train nanodet-m.pth, the size is 3.86M, but the size of model_best.pth which I trained with my custom dataset is 7.38M. 
I use the default config with nanodet-m.yml, is there anything I ignoring?

**Comment by RangiLyu** [comment]
The pre-train pth file is a model weight state dict. The size of float32 model weights is 3.8MB.
 The ncnn model is saved in fp16, which is half of the float32  model size. 
The model you got which is 7MB is a checkpoint file. It not only contains model weights, but also has optimizer and other parameters.
 You can use tools/export.py to get a 3.8MB onnx model.

**Comment by xiaotown123** [comment]
> The pre-train pth file is a model weight state dict. The size of float32 model weights is 3.8MB.
> The ncnn model is saved in fp16, which is half of the float32 model size.
> The model you got which is 7MB is a checkpoint file. It not only contains model weights, but also has optimizer and other parameters.
> You can use tools/export.py to get a 3.8MB onnx model.

OK, thanks for reply
