### ISSUE TITLE
Several problems on trying to run the demo

### ISSUE THREAD

**Issue by LEGoebel** [RangiLyu/nanodet#22]
Hello, 
since I can not get the demo to run I am asking here:
I run the command ([...] is just the path to that folder before with my personal name, so I leave it out):
python demo/demo.py image --config [...]/nanodet/config/nanodet-m.yml --model [...]/nanodet/nanodet_m/archive/data.pkl --path [...]/data/dog.jpg

Then I get the follwing errors:

model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
Traceback (most recent call last):
  File "demo/demo.py", line 106, in <module>
    main()
  File "demo/demo.py", line 80, in main
    predictor = Predictor(cfg, args.model, logger, device='cuda:0')
  File "demo/demo.py", line 31, in __init__
    ckpt = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

I followed all of the installation steps strictly. So I ran python setup.py develop and so on exactly as told. And after checking if the model file and so on are not empty I got this error. But since I am somewhat new to that I am now at a point where I can't resolve that issue myself. Can somebody help me to get at least a demo run?

**Comment by RangiLyu** [comment]
What is your pytorch version? Try to use pytorch1.6 or higher version. Pth format seems changed after 1.6

**Comment by bruce-almon** [comment]
I have the same problem with pytorch-1.7.0
I think you might need a specific version to get it to work

The error message is 

model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
Traceback (most recent call last):
  File "demo/demo.py", line 106, in <module>
    main()
  File "demo/demo.py", line 80, in main
    predictor = Predictor(cfg, args.model, logger, device='cuda:0')
  File "demo/demo.py", line 31, in __init__
    ckpt = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by RangiLyu** [comment]
> I have the same problem with pytorch-1.7.0
> I think you might need a specific version to get it to work
> 
> The error message is
> 
> model size is 1.0x
> init weights...
> => loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
> Finish initialize Lite GFL Head.
> Traceback (most recent call last):
> File "demo/demo.py", line 106, in
> main()
> File "demo/demo.py", line 80, in main
> predictor = Predictor(cfg, args.model, logger, device='cuda:0')
> File "demo/demo.py", line 31, in **init**
> ckpt = torch.load(model_path, map_location=lambda storage, loc: storage)
> File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
> return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
> File "[...]/anaconda3/envs/nanodet/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
> magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: A load persistent id instruction was encountered,
> but no persistent_load function was specified.

Make sure you download the nanodet_m.pth file, not a .pkl file. Google Drive incorrectly recognized the .pth file as a zip file and lead people to download the data.pkl in it.

**Comment by RangiLyu** [comment]
Pth file for torch<1.6 has been uploaded. Download link has been updated in readme.
