### ISSUE TITLE
shufflenetv2 1.5

### ISSUE THREAD

**Issue by DayBreak-u** [RangiLyu/nanodet#220]
我用ncnn测试过，shufflenetv2 1.5比shufflenetv2 1.0更快，因为前面shufflenetv2 1.0 都许多通道是58的，不是4的倍数，导致没有加速，建议up主替换，结果就是速度更快，效果更好

**Comment by RangiLyu** [comment]
哇，谢谢大佬！我来试试

**Comment by xiaotown123** [comment]
大佬哇，我也试试

**Comment by xiaotown123** [comment]
> 我用ncnn测试过，shufflenetv2 1.5比shufflenetv2 1.0更快，因为前面shufflenetv2 1.0 都许多通道是58的，不是4的倍数，导致没有加速，建议up主替换，结果就是速度更快，效果更好

请问大佬shufflenetv2 1.5的pretrained model哪里获得的啊？
