### ISSUE TITLE
Windows  vs2017编译出来结果很乱

### ISSUE THREAD

**Issue by AIwzx** [RangiLyu/nanodet#23]
用vs2017 编译出的结果非常差 有没有大神懂得
![result](https://user-images.githubusercontent.com/51156658/100219122-947c5f00-2f50-11eb-8c9f-cd6ad653b03d.jpg)

**Comment by RangiLyu** [comment]
请问能提供一下运行环境吗？包括操作系统和硬件环境以及显卡驱动版本

**Comment by RangiLyu** [comment]
测试一下9月份之前版本的ncnn，新版本貌似有些问题

**Comment by nihui** [comment]
已修复，更新下 ncnn 代码

**Comment by AIwzx** [comment]
@RangiLyu 你这么说很有道理啊  我linux上的是几个月之前编译的 一点问题没有   我重新编译一下
