### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six' (D:\PycharmProjects\nanodet-main\p3.8venv\lib\site-packages\torch\_six.py)

### ISSUE THREAD

**Issue by feiji110** [RangiLyu/nanodet#234]
![image](https://user-images.githubusercontent.com/43982513/117566214-ef150c00-b0e7-11eb-8a14-f65eb178797d.png)
![image](https://user-images.githubusercontent.com/43982513/117566238-0c49da80-b0e8-11eb-8d8c-f245dfc6fde9.png)
![image](https://user-images.githubusercontent.com/43982513/117566252-24215e80-b0e8-11eb-9065-2d63a9da9648.png)

**Comment by huy81194tk** [comment]
use pytorch version 1.8.0

**Comment by XinPeiHou** [comment]
Have you solved the problem？

**Comment by xellDart** [comment]
You cab take as base this commit to fix this

**Comment by mathpopo** [comment]
https://discuss.pytorch.org/t/cannot-import-name-int-classes-from-torch-six/126611
