### ISSUE TITLE
训练时候报错RuntimeError:Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by Robot-NX** [RangiLyu/nanodet#237]
您好，在使用0.3.0版本时出现这个问题，我用的torch版本是1.4.在requirelist中要求是大于1.6.请问这个NCCL与torch版本有关吗？
在使用0.3.0之前的版本时，torch1.4是可以训练和推理的。

**Comment by RangiLyu** [comment]
是PyTorch版本问题，更新到0.3.0之后PyTorch的版本依赖已经修改为 >= 1.6了
