### ISSUE TITLE
original pytorch or onnx model

### ISSUE THREAD

**Issue by kadirbeytorun** [RangiLyu/nanodet#24]
Could you please provide pretrained pytorch or onnx model weights also? I noticed you only shared converted ncnn models, but I would like to see the speed of inference on gpu/npu accelerated systems

**Comment by RangiLyu** [comment]
Actually the download link is in readme. Here is the link https://drive.google.com/file/d/1EhMqGozKfqEfw8y9ftbi1jhYu86XoW62/view?usp=sharing

**Comment by kadirbeytorun** [comment]
That is the torch jit model though, demo.py will not accept that. or am I doing something wrong?

I believe you need to upload the checkpoint weights. Not torch jit weights.

**Comment by RangiLyu** [comment]
This .pth file is saved with torch1.7. Pytorch have changed .pth format after 1.6. You can update your pytorch version. I may upload an old format later.

**Comment by kadirbeytorun** [comment]
Oh thats why then. I was trying it with 1.3 as requested in your requirements.txt

**Comment by kadirbeytorun** [comment]
> This .pth file is saved with torch1.7. Pytorch have changed .pth format after 1.6. You can update your pytorch version. I may upload an old format later.

Would it be possible to share the simplified onnx model perhaps then? Due to the restrictions of the SOC I am working at, I cannot use torch models above 1.2.0

**Comment by RangiLyu** [comment]
> > This .pth file is saved with torch1.7. Pytorch have changed .pth format after 1.6. You can update your pytorch version. I may upload an old format later.
> 
> Would it be possible to share the simplified onnx model perhaps then? Due to the restrictions of the SOC I am working at, I cannot use torch models above 1.2.0

Try this .pth file. It's for torch<1.6.  https://drive.google.com/file/d/10h-0qLMCgYvWQvKULqbkLvmirFR-w9NN/view?usp=sharing
