### ISSUE TITLE
redundant validation when using ddp mode?

### ISSUE THREAD

**Issue by AlbertiPot** [RangiLyu/nanodet#248]
Hi!

Really thank you for this wonderful work. 

When training it with ddp mode, according to the log, the validation seems to be executed twice independently on my 2 gpus. So I am wondering whether it is necessary to add  `if self.local_rank < 1:`  before line 83 in function `def validation_step(self, batch, batch_idx):` from the file _nanodet/nanodet/trainer/task.py_, in order to **reduce one redundant validation which is not the main rank process in the ddp mode**

Many thanks

validation log here ↓↓↓

![截屏2021-06-01 下午4 49 07](https://user-images.githubusercontent.com/33025006/120297884-1e402700-c2fc-11eb-8e0a-66351388dac6.png)

**Comment by RangiLyu** [comment]
I found that when using pytorch-lightning's DDP mode, the validation_epoch_end function won't gather all results across GPU. This results in the validation bug. But the training process seems to be okay. Refer to a similar issue https://github.com/PyTorchLightning/pytorch-lightning/issues/7697

**Comment by RangiLyu** [comment]
Fixed in #254
