### ISSUE TITLE
自己的训练集结果很糟糕

### ISSUE THREAD

**Issue by jie311** [RangiLyu/nanodet#25]
您好，我更换了骨干网络vovnet-19，pan和head都没有变（类别设置为bdd100k提供的类别），不加载imagenet预训练参数的情况下直接训练，效果非常糟糕，70个epoch的ap只有18左右，而yolov5s同样的骨干能到40，想问一下大概是什么原因

**Comment by RangiLyu** [comment]
NanoDet的PAN和Head都是极度轻量化后的，只有非常少的卷积，而yolov5s的head使用了BottleneckCSP，PAN使用的Concat，计算量不在一个数量级上。而且nanodet只使用了320分辨率输入。你可以尝试修改head，使用更强的卷积模块做检测头并且增大输入分辨率。同时，如果backbone不加载预训练权重则需要更多的epoch去训练。
