### ISSUE TITLE
demo on cpu

### ISSUE THREAD

**Issue by maylad31** [RangiLyu/nanodet#253]
Hi, the demo works excellent on gpu. But on cpu i set device="cpu" and disable all cuda related commands(torch.cuda.synchronize) but still there is no prediction. I get skip loading parameter warnings, but no detection. It is as if model is not loaded properly. Thanks

**Comment by maylad31** [comment]
There was a difference in my conf file as compared to training. Solved. Thanks

**Comment by zzzwww** [comment]
> There was a difference in my conf file as compared to training. Solved. Thanks

Hello, I have the same problem with you, could you please tell me how you solve it, thank you very much.
