### ISSUE TITLE
训练完10个epoch开始测试的时候报错：list object has no attribute cpu

### ISSUE THREAD

**Issue by cjnewstar111** [RangiLyu/nanodet#26]
File "nanodet-main/nanodet/trainer/trainer.py", line 89, in run_epoch
    results[meta['img_info']['id'].cpu().numpy()[0]] = dets
AttributeError: 'list' object has no attribute 'cpu'

**Comment by lilin1234567** [comment]
me too

**Comment by zaoyifan** [comment]
me too

**Comment by RangiLyu** [comment]
Please provide more details such as dataset, training env, pytorch version and other useful information.

**Comment by zaoyifan** [comment]
> Please provide more details such as dataset, training env, pytorch version and other useful information.

My own dataset, windows10, pytorch 1.7.0 and no other changes. This error is generated during validation.

**Comment by zaoyifan** [comment]
![2020-11-26_203020](https://user-images.githubusercontent.com/37692927/100351395-581b3280-3026-11eb-8989-d0f4263e903e.png)

**Comment by RangiLyu** [comment]
COCO image id should be a number, not a string. Please check your json file. 
Here is another tool for converting voc xml to coco json. https://github.com/jinfagang/alfred

**Comment by zhoushuang66** [comment]
验证时候会报错。
![image](https://user-images.githubusercontent.com/32835361/100353126-03c58200-3029-11eb-8d86-a1a0dee517b0.png)
我训练只有俩类，val.json中，不算背景类别的话，只有0和1类别了。

**Comment by zaoyifan** [comment]
> COCO image id should be a number, not a string. Please check your json file.
> Here is another tool for converting voc xml to coco json. https://github.com/jinfagang/alfred

Thanks

**Comment by AsatledFish** [comment]
> > COCO图片ID应该是数字，而不是字符串。请检查您的json文件。
> > 这是另一个将voc xml转换为coco json的工具。https://github.com/jinfagang/alfred
> 
> 谢谢

Is it successful?

**Comment by zaoyifan** [comment]
> > > COCO图片ID应该是数字，而不是字符串。请检查您的json文件。
> > > 这是另一个将voc xml转换为coco json的工具。https://github.com/jinfagang/alfred
> > 
> > 
> > 谢谢
> 
> Is it successful?

Yes

**Comment by zhoushuang66** [comment]
thanks

**Comment by zhoushuang66** [comment]
thanks，then,i test it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RangiLyu/nanodet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 上午10:12
收件人:&nbsp;"RangiLyu/nanodet"<nanodet@noreply.github.com&gt;;
抄送:&nbsp;"功成子"<2809836286@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [RangiLyu/nanodet] 训练完10个epoch开始测试的时候报错：list object has no attribute cpu (#26)





  
COCO image id should be a number, not a string. Please check your json file.
 Here is another tool for converting voc xml to coco json. https://github.com/jinfagang/alfred
  
Thanks

**Comment by liulonghoi** [comment]
> 验证时候会报错。
> ![image](https://user-images.githubusercontent.com/32835361/100353126-03c58200-3029-11eb-8d86-a1a0dee517b0.png)
> 我训练只有俩类，val.json中，不算背景类别的话，只有0和1类别了。打印出来label是0，1，2三个类别。

你好，我的程序也在验证的时候出现了和你一样的问题，也是列表超出索引，请问你是怎么解决这个问题的？

**Comment by zhoushuang66** [comment]
我的是类别数错了,修改完就好了。

**Comment by eeric** [comment]
labels: txt-->xml-->json
This project support to Nanodet project to make official labels.
https://github.com/eeric/yolo2voc2coco

**Comment by zhoushuang66** [comment]
thanks

**Comment by RangiLyu** [comment]
Try to use xml_dataloader instead of coco_dataloader.
