### ISSUE TITLE
Cannot find blob with name: dis_pred_stride_8 

### ISSUE THREAD

**Issue by TTMRonald** [RangiLyu/nanodet#269]
使用demo_ncnn和demo_openvino测试转换预训练模型，转换过程均正常，但是预测时候出现问题，想问下怎么解决？

``` 
# demo_ncnn
find_blob_index_by_name input.1 failed
Try
find_blob_index_by_name dis_pred_stride_8 failed
Try
find_blob_index_by_name cls_pred_stride_8 failed
```

``` 
# demo_openvino
start init model
success
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
what(): Cannot find blob with name: dis_pred_stride_8
```

发现onnx模型存在dis_pred_stride_8等节点，但是转换后的ncnn模型这几个节点消失
onnx网络结构：
<img width="480" alt="onnx" src="https://user-images.githubusercontent.com/18680409/123786177-f9939b00-d90b-11eb-9a2a-480630e14ceb.png">
ncnn网络结构：
<img width="327" alt="ncnn" src="https://user-images.githubusercontent.com/18680409/123786264-162fd300-d90c-11eb-8546-2efb4d65f657.png">

**Comment by LeiGan0215** [comment]
遇到同样的问题，请问下有人解决了这个问题吗，这个会不会和opset_version有关系呢

**Comment by LeiGan0215** [comment]
兄弟，我解决这个问题了，我是跑那个openvino出现的问题，我按照xml里面的name改了下头文件对应的heads_info_，就可以了

**Comment by TTMRonald** [comment]
@LeiGan0215 已解决，非常感谢！

**Comment by aboy2018** [comment]
> 兄弟，我解决这个问题了，我是跑那个openvino出现的问题，我按照xml里面的name改了下头文件对应的heads_info_，就可以了

应该改成Transpose_333还是Transpose_333/sink_port_0呢

**Comment by doubiydd** [comment]
> @LeiGan0215 已解决，非常感谢！

请问一下大佬怎么解决的呀。。。好少攻略我蒙了

**Comment by doubiydd** [comment]
> 

您好！请问解决了吗
