### ISSUE TITLE
Size mismatch when loading pre-trained weights and changing num_classes

### ISSUE THREAD

**Issue by stuarteiffert** [RangiLyu/nanodet#274]
The issue described in https://github.com/RangiLyu/nanodet/issues/231 still exists when training a pretrained ckpt on a dataset with a different number of classes. 

This exists for both nanodet_g and nanodet_m, I get an error regarding  `size mismatch for model.head.gfl_cls` when attempting to train.

The tested ckpts are the ones linked in the README.md: https://drive.google.com/file/d/1ZkYucuLusJrCb_i63Lid0kYyyLvEiGN3/view and https://drive.google.com/file/d/1f2lH7Ae1AY04g20zTZY7JS_dKKP37hvE/view

**Comment by stuarteiffert** [comment]
Pull request created to skip loading of head if shape mismatch https://github.com/RangiLyu/nanodet/pull/275

**Comment by RangiLyu** [comment]
Fixed in #288
