### ISSUE TITLE
关于BN

### ISSUE THREAD

**Issue by liushuai839** [RangiLyu/nanodet#28]
你好, 我想问一下在推理的时候,BN和卷积层合并具体是怎么实现的呢? 相关代码在哪里啊
谢谢

**Comment by RangiLyu** [comment]
https://github.com/Tencent/ncnn 使用ncnnoptimize优化模型

**Comment by liushuai839** [comment]
> https://github.com/Tencent/ncnn 使用ncnnoptimize优化模型

我如果不想用ncnn这个框架,想要在自己的网络中实现BN和卷积层的融合呢

**Comment by niaoyu** [comment]
> > https://github.com/Tencent/ncnn 使用ncnnoptimize优化模型
> 
> 我如果不想用ncnn这个框架,想要在自己的网络中实现BN和卷积层的融合呢

参考yolov5

**Comment by zhangkui669** [comment]
> > > https://github.com/Tencent/ncnn 使用ncnnoptimize优化模型
> > 
> > 
> > 我如果不想用ncnn这个框架,想要在自己的网络中实现BN和卷积层的融合呢
> 
> 参考yolov5

会比较麻烦，yolo-multi-backbone-attention的模型结构定义跟这个类似，用它里面的models.py里的fuse改动量少一些
