### ISSUE TITLE
Different input size

### ISSUE THREAD

**Issue by Zrufy** [RangiLyu/nanodet#281]
anyone used to train nanodet with different input size?LIke 224,192,160?
if yes how you change the in_channels for the pan?

**Comment by RangiLyu** [comment]
Input size does not affect the `in_channels` setting for the PAN. `in_channels` is only related to the output channels in backbone.

**Comment by Zrufy** [comment]
so let's say that if I wanted to train a network at 160 I would just have to put 160 in the input size.
The dataset will be enough to put it like this without resizing the images right? Or do I first have to resize to 160 and then the training?

**Comment by Zrufy** [comment]
Duplicate of #284
