### ISSUE TITLE
运行demo.py时,出现了一个小问题.

### ISSUE THREAD

**Issue by lidongliang666** [RangiLyu/nanodet#29]
我的运行环境:
cuda==10.1 
pytorch==1.7
torchvision==0.8.0
当我运行"python demo/demo.py image --config CONFIG_PATH --model MODEL_PATH --path IMAGE_PATH",尝试推理图片时,
出现错误:
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /root/project/torchvision/csrc/vision.cpp:59 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradXLA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
Tracer: fallthrough registered at /pytorch/torch/csrc/jit/frontend/tracer.cpp:967 [backend fallback]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

但是当我把:/nanodet/nanodet/model/module/nms.py  batched_nms(boxes, scores, idxs, nms_cfg, class_agnostic=False)函数改后:
    
    boxes_for_nms = boxes_for_nms.cpu()
    scores = scores.cpu()
    boxes = boxes.cpu()
    split_thr = nms_cfg_.pop('split_thr', 10000)
    if len(boxes_for_nms) < split_thr:
        # dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
        keep = nms(boxes_for_nms, scores, **nms_cfg_)
        boxes = boxes[keep]
        # scores = dets[:, -1]
        scores = scores[keep]

demo.py正常运行.

**Comment by guo-pu** [comment]
请问demo.py运行时，CONFIG_PATH 在哪里吗？下载权重后是nanodet_m.pth文件的

**Comment by lidongliang666** [comment]
首先我修改了 nanodet-m.yml  配置文件  save_dir: save/.

运行时具体的命令为:
python demo/demo.py image --config config/nanodet-m.yml --model save/nanodet_m.pth --path /home/ldl/coco/images/coco_test/000000016451.jpg

程序前几行的输出为:
model size is  1.0x
init weights...
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize Lite GFL Head.
[root][11-30 17:37:17]INFO:Press "Esc", "q" or "Q" to exit.
/home/ldl/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
forward time: 0.107s | Traceback (most recent call last):

**Comment by guo-pu** [comment]
谢谢我跑起来了，发现速度确实挺快的，但是识别精度比YOLOv4差远了

**Comment by zoufangyu1987** [comment]
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth

为什么加载shufflenet的pth，怎么不是加载nanodet.pth，跑出来效果明显不好不对，哪里需要设置吗？

**Comment by zoufangyu1987** [comment]
@lidongliang666 @guo-pu 这个问题怎么解决？

**Comment by lidongliang666** [comment]
@zoufangyu1987训练时, 加载shufflenet的pth是因为,要用预训练模型初始化权重,做热身训练.
预测时要下载作者在Coco上训练好的nanodet.pth.  
![image](https://user-images.githubusercontent.com/26034924/101120347-61109300-3628-11eb-8c35-c00551e11045.png)
用 --path IMAGE_PATH  来指定nanodet.pth路径即可,使用作者在Coco数据集上训练好的权重.

**Comment by guo-pu** [comment]
@zoufangyu1987 如果是PyTorch 版本的，可以直接参考这里：https://github.com/guo-pu/NanoDet-PyTorch
该代码基于NanoDet项目进行小裁剪，专门用来实现Python语言、PyTorch 版本的代码，下载直接能使用，支持图片、视频文件、摄像头实时目标检测。

**Comment by zoufangyu1987** [comment]
@lidongliang666 @guo-pu 
好的，谢谢！
