### ISSUE TITLE
error while evaluation?

### ISSUE THREAD

**Issue by angryhen** [RangiLyu/nanodet#302]
task.py -- validation_epoch_end:
"Trainer" object has no attribute 'use_ddp'

**Comment by ForeverPs** [comment]
I also meet this problem. How do you solve this?

**Comment by RangiLyu** [comment]
What is the version of pytorch-lightning you using?

**Comment by ankandrew** [comment]
@RangiLyu in 1.4.0, some attributes like use_ddp got removed.

> Removed deprecated trainer attributes - on_cpu, on_tpu, use_tpu, on_gpu, use_dp, use_ddp, use_ddp2, use_horovod, use_single_gpu 

[Source](https://github.com/PyTorchLightning/pytorch-lightning/pull/7501).
