### ISSUE TITLE
Excuse me ! how to find the file "nanodet_demo" in demo_ncnn?

### ISSUE THREAD

**Issue by dddd247** [RangiLyu/nanodet#31]
I want to use the application of performing ncnn in "demo_ncnn" file ?
But I can not find the "nanodet_demo" in this file, can you upload the "nanodet_demo", please?

**Comment by RangiLyu** [comment]
Please following the c++ demo guide to complie  the executable file.

**Comment by dddd247** [comment]
Thanks !

**Comment by zhangxiaohuixuhao** [comment]
When I execute the make command, an error is reported.

Scanning dependencies of target nanodet_demo
[ 33%] Building CXX object CMakeFiles/nanodet_demo.dir/main.cpp.o
In file included from /home/mpe/zhanghui/nanodet/demo_ncnn/main.cpp:6:0:
/home/mpe/zhanghui/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
/home/mpe/zhanghui/nanodet/demo_ncnn/main.cpp: In function ‘int image_demo(NanoDet&, const char*)’:
/home/mpe/zhanghui/nanodet/demo_ncnn/main.cpp:237:63: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘cv::String’ [-Wformat=]
             fprintf(stderr, "cv::imread %s failed\n", img_name);
                                                               ^
[ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/nanodet.cpp.o
In file included from /home/mpe/zhanghui/nanodet/demo_ncnn/nanodet.cpp:6:0:
/home/mpe/zhanghui/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
[100%] Linking CXX executable nanodet_demo
/usr/bin/ld: cannot find -lncnn.lib
/usr/bin/ld: cannot find -lglslang.lib
/usr/bin/ld: cannot find -lOGLCompiler.lib
/usr/bin/ld: cannot find -lOSDependent.lib
/usr/bin/ld: cannot find -lSPIRV.lib
collect2: error: ld returned 1 exit status
CMakeFiles/nanodet_demo.dir/build.make:138: recipe for target 'nanodet_demo' failed
make[2]: *** [nanodet_demo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nanodet_demo.dir/all' failed
make[1]: *** [CMakeFiles/nanodet_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kevinchan04** [comment]
Sorry, I just followed the c++ tutorial to compile the demo_ncnn, but after I built it successfully.

> [ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/nanodet.cpp.o
[ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/main.cpp.o
In file included from /home/pi/xiaodong/nanodet/demo_ncnn/nanodet.cpp:6:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
In file included from /home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:6:
/home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
 typedef struct HeadInfo
 ^~~~~~~
[100%] Linking CXX executable nanodet_demo
[100%] Built target nanodet_demo


Then, I tried the command `nanodet_demo 1 my_img.jpg`, it showed the error:

> bash: nanodet_demo: command not found

Could you tell me how to solve it problem? Thanks @RangiLyu

**Comment by Lilin-Xu** [comment]
> Sorry, I just followed the c++ tutorial to compile the demo_ncnn, but after I built it successfully.
> 
> > [ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/nanodet.cpp.o
> > [ 66%] Building CXX object CMakeFiles/nanodet_demo.dir/main.cpp.o
> > In file included from /home/pi/xiaodong/nanodet/demo_ncnn/nanodet.cpp:6:
> > /home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
> > typedef struct HeadInfo
> > ^~~~~~~
> > In file included from /home/pi/xiaodong/nanodet/demo_ncnn/main.cpp:6:
> > /home/pi/xiaodong/nanodet/demo_ncnn/nanodet.h:12:1: warning: ‘typedef’ was ignored in this declaration
> > typedef struct HeadInfo
> > ^~~~~~~
> > [100%] Linking CXX executable nanodet_demo
> > [100%] Built target nanodet_demo
> 
> Then, I tried the command `nanodet_demo 1 my_img.jpg`, it showed the error:
> 
> > bash: nanodet_demo: command not found
> 
> Could you tell me how to solve it problem? Thanks @RangiLyu

Have you solved the problem? I have the same problem. If you have worked out it, could you tell me how to solve it problem?
