### ISSUE TITLE
num_classes for one class detection 

### ISSUE THREAD

**Issue by cannguyen275** [RangiLyu/nanodet#32]
Hi,

To train a detector for one class only, should I set `num_classes `as `1` or `2`? (because I'm confusing with background class)
In my case, it is a dick detector. Should I set `class_names `as `['dick', 'background'] `or just `['dick']`?

I successfully start to train my model but appearing some errors related to the above things.

Thanks so much for your helps!
Me,

**Comment by RangiLyu** [comment]
Set num_classes: 1

**Comment by cannguyen275** [comment]
Thanks for this quick support! It works to train right now!
Even missing my "class_names" question but I have found the answer myself.
Thanks again for this nice works!

**Comment by tommy3266** [comment]
@RangiLyu 请问训练自己的数据，假设是两个类别，设置num_classes=2，class_names列表也填入对应的类了，那么对应的类别编码在哪里看呢
