### ISSUE TITLE
FPS in 1080ti  just 30-50fps for single_class detection

### ISSUE THREAD

**Issue by xxy90** [RangiLyu/nanodet#33]
![image](https://user-images.githubusercontent.com/32832726/100423834-a2a0bb80-30c7-11eb-8d20-dafd626012d9.png)

**Comment by RangiLyu** [comment]
Make sure you turn on cudnn acceleration.
Pull the latest version of nanodet or change 
```python   
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
```
in demo.py to
```python
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = True
```
By the way, pytorch is a training framework, not designed for inference. If you want test better inference speed on GPU, try to use C++ demo. C++ demo using ncnn vulkan as backend.
