### ISSUE TITLE
pth文件转onnx文件出错

### ISSUE THREAD

**Issue by quanzhang2020** [RangiLyu/nanodet#34]
rt
环境：
win10
pytorch 1.7.0
onnx-simplifier  0.2.19
protobuf     3.14.0
执行python -m onnxsim ./nanodet_m.pth ./nanodet.onnx 报错：google.protobuf.message.DecodeError: Field number 0 is illegal.

**Comment by kadirbeytorun** [comment]
You are supposed to first export onnx by export.py, then use that output.onnx to get your simplified.onnx

You cannot use pth file to get onnx, pth is just network weights.

**Comment by quanzhang2020** [comment]
ok，done， thanks！
