### ISSUE TITLE
FPS on cpu i5 is not high

### ISSUE THREAD

**Issue by awl-anht-nguyen** [RangiLyu/nanodet#349]
Hi @RangiLyu, thank you for your work.
I trained NanoDet-m on my own dataset with head and face labels, and exported to onnx successfully. But when I did benchmark onnx model on my computer Mac pro cpu core i5, the model got only 32 fps. I used code in `demo_ncnn/python/demo_ncnn.py`
I wondered it was not high and it will got higher if I convert onnx to mnn model, right?
Because your model had small enough size, so I thought that your model could get higher fps than 32.
![Screen Shot 2021-11-30 at 17 06 12](https://user-images.githubusercontent.com/84887915/144027099-03a6ce61-ccea-40b1-8184-4c48d95cf6de.png)

**Comment by RangiLyu** [comment]
To get better performance on Intel CPU, please use openvino.

**Comment by awl-anht-nguyen** [comment]
@RangiLyu How many fps you could get when running MNN on arm chipset of NanoDet-m model?

**Comment by awl-anht-nguyen** [comment]
Hi @RangiLyu, I ran MNN model on my arm device having 6 threads and got only 9 fps instead of 97 in your README.md. I used your `demo_mnn` code to compute fps. Had I was wrong in which step?

**Comment by superbayes** [comment]
兄弟,请将语言由python改为c++,在测试推理速度

**Comment by awl-anht-nguyen** [comment]
@superbayes Thanks for your suggestion.
Which device did you test speed using cpp script? And how many fps did you get? Thank you.

**Comment by RangiLyu** [comment]
> @superbayes Thanks for your suggestion. Which device did you test speed using cpp script on? And how many fps did you get? Thank you.

97fps is benchmarked on Arm A76 4 threads with ncnn fp16 inference.
