### ISSUE TITLE
关于NMS的效率问题

### ISSUE THREAD

**Issue by zhangkui669** [RangiLyu/nanodet#35]
刚开始看nanodet的相关论文
对于hxw的feature上，FCOS实际上预测了HXWXC的一个类别概率，还有一个center-ness，这个center-ness的定义实际上有点儿类似centernet的heatmap真值，在真值目标框中心点周围算一个高斯分布，centernet是在HXWXC的heatmap上通过在做了一个3x3的max-pooling来替代NMS
那问题来了，是不是可以通过HXWXC的类别预测 x HXWX1的centerness，然后在这上面做max-pooling来替代后处理中耗时的NMS计算呢？

**Comment by RangiLyu** [comment]
NMS latency in NanoDet cpp demo is less than 0.01 ms.
