### ISSUE TITLE
使用 demo_ncnn python 推理为空

### ISSUE THREAD

**Issue by justiceeem** [RangiLyu/nanodet#350]
使用提供的 ncnn bin 和 params 在 demo_python 的 python 脚本验证，出现 ncnn 推理结果为空。
结果如图：
![image](https://user-images.githubusercontent.com/50164570/144195077-c7f0487d-9f70-4fc8-9946-f504c4d62460.png)

**Comment by momohuangsha** [comment]
@justiceeem  请问你解决这个问题了吗？我也遇到了一样的错误
