### ISSUE TITLE
shufflenetv2 in nanodet is different from that in mmcls

### ISSUE THREAD

**Issue by Senwang98** [RangiLyu/nanodet#352]
Hi, @RangiLyu 
Sorry to disturb you again, 
The shufflenetv2 in this repo is different from that in mmcls.
In `mmcls.shufflenetv2/Line 216`, 
https://github.com/open-mmlab/mmclassification/blob/e3cf1881bbf322c388bd2db8f7dae316dc8a1c33/mmcls/models/backbones/shufflenet_v2.py#L216
**it seems that mmcls add another small conv branch which hence has higher GFlops.**(I found this thing when I check `mmdet's nanodet` vs. `this repo`)

(I will check it twice. Maybe I am wrong!
Wishing for your reply.

**Comment by RangiLyu** [comment]
When setting out_indices=(0, 1, 2) in mmcls backbone, the last layer will not be used.

**Comment by Senwang98** [comment]
Yes, you are right!
