### ISSUE TITLE
question about `keep_ratio`

### ISSUE THREAD

**Issue by Laughing-q** [RangiLyu/nanodet#382]
I notice that `keep_ratio`=False in training configs, does this mean that the images are stretched during training instead of keeping aspect ratio and padding?
is this a trick or something?

**Comment by Senwang98** [comment]
@Laughing-q 
About one month ago, I tried to reproduct Nanodet and Picodet based on MMdet2. 
I found only if you set keep-ratio=False, then the mAP is the same as official nanodet!
So, I think this is one trick. 
Keep-retio=True is 0.4 mAP lower than that =False when using Nanodet-0.5x

**Comment by RangiLyu** [comment]
`keep_ratio=False` can achieve higher mAP on COCO (around 0.5 mAP). But this may not be suitable for all datasets.

**Comment by Laughing-q** [comment]
@RangiLyu @Senwang98 Thanks.
