### ISSUE TITLE
测试mAP

### ISSUE THREAD

**Issue by Daipuwei** [RangiLyu/nanodet#39]
目前给出的mAP计算指标是使用pycocotool API计算得到的AP50和AP75，但是无法得到各个类别的AP指标，不知博主能否开发计算各个类别的AP指标的脚本哈

**Comment by zhangkui669** [comment]
yolov5: https://github.com/ultralytics/yolov5/blob/master/test.py
centernet: https://github.com/xingyizhou/CenterNet/blob/master/src/test.py

你的需求基本上每个开源检测方案里都有
