### ISSUE TITLE
Which paper it belongs to?

### ISSUE THREAD

**Issue by qgh1223** [RangiLyu/nanodet#4]
Which paper it belongs to?

**Comment by qgh1223** [comment]
YOLO?But you say it is anchor free.It can't be yolov1, right

**Comment by RangiLyu** [comment]
The whole model architecture is base on FCOS, and using Generalized Focal Loss for classification and box regression.
You can refer to these papers: 
[Fcos: Fully convolutional one-stage object detection](http://openaccess.thecvf.com/content_ICCV_2019/papers/Tian_FCOS_Fully_Convolutional_One-Stage_Object_Detection_ICCV_2019_paper.pdf)
[Generalized Focal Loss: Learning Qualified and Distributed Bounding Boxes for Dense Object Detection](https://arxiv.org/pdf/2006.04388.pdf)
