### ISSUE TITLE
Support of several backbones with NanoDet-Plus architecture

### ISSUE THREAD

**Issue by rose-jinyang** [RangiLyu/nanodet#400]
Hello
How are you?
Thanks for contributing to this project.
Could u support of several backbones with NanoDet-Plus architecture?

**Comment by andongchen** [comment]
I also have a question, have you try mobilenetv3 backbone, Could it improve Map.
@RangiLyu

**Comment by RangiLyu** [comment]
PR #399 introduces a new feature that NanoDet can directly use hundreds of pre-trained backbones in timm https://github.com/rwightman/pytorch-image-models
