### ISSUE TITLE
自己数据集，训练中的损失问题

### ISSUE THREAD

**Issue by crossover10** [RangiLyu/nanodet#43]
我自己的一个4 classes 的数据集有1万张，
第一轮：warmup|Iter(1/300)| lr:1.44e-02| loss_qfl:0.4034| loss_bbox:1.4174| loss_dfl:0.5207|
停止训练时：train|Epoch100/300|Iter66238(600/663)| lr:1.40e-07| loss_qfl:0.3369| loss_bbox:0.6454| loss_dfl:0.2716| 

我想问一开始的时候损失就已经降得这么低，这个情况合理吗？
验证集的ap也很低
感谢您的贡献

**Comment by leozicai** [comment]
一开始这个损失应该没什么问题。我觉得问题出在你的learning rate上，在第100epoch你的lr就降到1.40e-07，这么低的学习率loss当然降不下去。建议修改config文件lr_schedule的milestones，总共300epoch，感觉设两个milestones[180,230]，gamma=0.1即可吧。

**Comment by crossover10** [comment]
感谢您的回复

**Comment by RangiLyu** [comment]
收敛需要保证足够的step数，coco是11万张，如果在1万张上训练，至少需要10倍epoch数，尝试调大epoch
