### ISSUE TITLE
您好，torch 1.3版本dataloader一直取不到值，在输出warming up之后一直死循环

### ISSUE THREAD

**Issue by lzylzy2223** [RangiLyu/nanodet#44]
请问这个问题该怎么解决呢

**Comment by RangiLyu** [comment]
可以定位到在哪个函数死循环吗？

**Comment by lzylzy2223** [comment]
这个问题已经解决了，低版本torch不支持多线程，把workers_per_gpu=0就能解决了

**Comment by lzylzy2223** [comment]
> 可以定位到在哪个函数死循环吗？

这个问题已经解决了，低版本torch不支持多线程，把workers_per_gpu=0就能解决

**Comment by zlszhonglongshen** [comment]
> > 可以定位到在哪个函数死循环吗？
> 
> 这个问题已经解决了，低版本torch不支持多线程，把workers_per_gpu=0就能解决

你好 我按照这种方式设置以后，FileNotFoundError: Cant load image! Please check image path!

**Comment by lzylzy2223** [comment]
> > > 可以定位到在哪个函数死循环吗？
> > 
> > 
> > 这个问题已经解决了，低版本torch不支持多线程，把workers_per_gpu=0就能解决
> 
> 你好 我按照这种方式设置以后，FileNotFoundError: Cant load image! Please check image path!

把路径打出来看看，路径写错了
