### ISSUE TITLE
train with multi-class, only output one-class in inferencing 

### ISSUE THREAD

**Issue by gongsuming** [RangiLyu/nanodet#457]
Multi-class of data are used in training, but only one class result will be produced in inferencing, and the other categories are all empty.
Why is this happening?
Thank you in advance.

**Comment by Sanath1998** [comment]
> Multi-class of data are used in training, but only one class result will be produced in inferencing, and the other categories are all empty. Why is this happening? Thank you in advance.

Did u get an answer for this?

**Comment by ShubNMahajan** [comment]
@gongsuming Can you tell me how you resolved it
