### ISSUE TITLE
how can I convert model parameters to .param and .bin files

### ISSUE THREAD

**Issue by busyyang** [RangiLyu/nanodet#46]
Thanks for sharing. I have test the model in android studio, and it works well. But I have a question, when I trained my model with extension .pth. How can I convert the model file into .param and .bin files. 

It may be a easy question, but I am a pytorch starter. Looking forward your reply.

**Comment by RangiLyu** [comment]
Plz refer to this issue.  #40

**Comment by busyyang** [comment]
Ok, it is helpful.
