### ISSUE TITLE
代码更改实时生效问题

### ISSUE THREAD

**Issue by ghoshaw** [RangiLyu/nanodet#468]
你好，我想问下我在正常的训练过程中，改了数据读取模块，为什么直接就生效了呢，然后本来正在运行的代码会在我改的地方报错了，因为我改动了输入size。为什么这个会实时更新锕，这个设置怎么关掉呢？

**Comment by RangiLyu** [comment]
一般是因为multi processing的启动方式是spawn导致的，spawn会从文件启动进程，可以修改成fork
