### ISSUE TITLE
Information when load the model

### ISSUE THREAD

**Issue by Firegreat123** [RangiLyu/nanodet#504]
![image](https://user-images.githubusercontent.com/103976695/228101511-0b019c1f-d2af-4819-9abd-82d4143d2ba1.png)
Is this no parameters phenomenon normal?

**Comment by RangiLyu** [comment]
`aux_fpn` and `aux_head` are auxiliary modules used only during training. If you are not resuming a training process, there is no need to load these parts.

**Comment by Firegreat123** [comment]
Thank you, really appreciate!
