### ISSUE TITLE
在i7 32核处理器上测试 320输入推理速度为34毫秒，416输入为52毫秒，gpu上推理时间为8毫秒

### ISSUE THREAD

**Issue by lovelychao** [RangiLyu/nanodet#51]
请问下是否是需要设置什么参数才能达到公布的推理速度，谢谢

**Comment by RangiLyu** [comment]
ncnn在ARM上的优化比x86好很多，pc上的速度不一定非常快

**Comment by eeric** [comment]
了解

**Comment by CBIR-LL** [comment]
@RangiLyu @lovelychao 在webcamera不动的情况下【想保证输入图像不变】，测试您提供的demo_ncnn示例，检测耗时会从6ms逐渐攀升到18ms附近，感觉很奇怪。查了一下cpu和内存的占用，没有发现明显的波动。 哪里需要注意或者改动的地方吗？
`		auto start = std::chrono::system_clock::now();
        auto results = detector.detect(resized_img, 0.4, 0.5);
		auto end = std::chrono::system_clock::now();
		auto time_use = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
		std::cout << "Time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;
		int fps = 1000 / time_use;`

**Comment by RangiLyu** [comment]
> @RangiLyu @lovelychao 在webcamera不动的情况下【想保证输入图像不变】，测试您提供的demo_ncnn示例，检测耗时会从6ms逐渐攀升到18ms附近，感觉很奇怪。查了一下cpu和内存的占用，没有发现明显的波动。 哪里需要注意或者改动的地方吗？
> ![image](https://user-images.githubusercontent.com/12853603/101467002-bc21ed00-397c-11eb-8641-b06596e84d69.png)
> 

或许是负载过高降频了
