### ISSUE TITLE
请教下您在模型调参上的思路

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#52]
所有设置都使用您提供的默认值，仅修改使用了多路GPU，最终70epoch后mAP只有0.16，翻看评论得知您是调整lr decay来优化模型参数的，请教下，您在训练模型的时候，关于初始化、优化器和学习策略都是怎么考虑的呢，比如时下流行的xavier初始化，Adam优化器，cosine learning rate等等有进行过尝试么，有没有可能得到更高的精度？

**Comment by RangiLyu** [comment]
初始化是加载imagenet预训练模型的，调参都是在sgd上调的，具体方式就是另一个评论里说的，用初始的大lr训练比较多的epoch，当大lr情况下的mAP不再上升之后，选取最高mAP的checkpoint进行lr decay继续训练。多卡大batch训练的话总step数变少，确实是会导致mAP略微下降，但是我在总共70epoch下是能训练到19多mAP。目前给出的20.6是在125epoch第一次decay，总共训练150epoch得到的。

**Comment by connorchen** [comment]
感谢回复，我刚注意到您为了提升mAP在12.1号修改了配置文件，不过这里面的list似乎应该是递增的
-    milestones: [40,55,60,65]
+   milestones: [130,160,150,155]  <--- 非递增

**Comment by RangiLyu** [comment]
Already fixed in commit 0c7770a4fe06d95386d85c8fb542bb6736e945ab
