### ISSUE TITLE
关于参数量的问题

### ISSUE THREAD

**Issue by PlasticBagBand** [RangiLyu/nanodet#521]
您好，我在训练nanodet-plus的时候发现它输出的参数大小是4.2M，但是提供的表格和文档中的参数大小是1.17M，请问这是怎么回事呢？谢谢！
![捕获](https://github.com/RangiLyu/nanodet/assets/126455029/7896516b-c042-4d55-a454-20293dfb6f24)
![微信图片_20230708215206](https://github.com/RangiLyu/nanodet/assets/126455029/b5e1b3e8-782b-4d17-9596-4c868d050c38)

**Comment by RangiLyu** [comment]
训练时的参数量包含了额外的辅助头，辅助头的参数在推理时是不使用的

**Comment by PlasticBagBand** [comment]
好的知道了谢谢
