### ISSUE TITLE
关于数据normalize的问题

### ISSUE THREAD

**Issue by busyyang** [RangiLyu/nanodet#53]
我使用demo_ncnn编译C++项目时候，发现[nanodet.cpp](https://github.com/RangiLyu/nanodet/blob/main/demo_ncnn/nanodet.cpp)中有减去均值，除方差的操作，但是在python代码中没看到，配置文件中有类似的语句`normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]`,但是和cpp文件中的值是不一样的。这个是怎么回事么？
~~~
void NanoDet::preprocess(cv::Mat& image, ncnn::Mat& in)
{
    int img_w = image.cols;
    int img_h = image.rows;

    in = ncnn::Mat::from_pixels(image.data, ncnn::Mat::PIXEL_BGR, img_w, img_h);

    // 这个值不应该是在训练模型的时候获得的吗，但是python代码中没找到类似的数字
    const float mean_vals[3] = { 104.04f, 113.9f, 119.8f };
    const float norm_vals[3] = { 0.013569f, 0.014312f, 0.014106f };
    in.substract_mean_normalize(mean_vals, norm_vals);
}
~~~

**Comment by RangiLyu** [comment]
这确实是我写错了，谢谢指正。cpp里面用了以前另一个模型的均值和方差忘记改过来了

**Comment by RangiLyu** [comment]
已在 commit c3aa0684b524fbfcae3e8e3f282628064430e39f 修正
