### ISSUE TITLE
Why the training phase is quite slow with V100 GPU?

### ISSUE THREAD

**Issue by ForeverPs** [RangiLyu/nanodet#530]
I have two V100 GPUs, however, the training phase is extremely slow with only 643 images? I wonder the reason.

**Comment by ForeverPs** [comment]
I find the reason, I suggest the author to modify the code: nanodet/data/dataset/yolo.py, line 97, img = cv2.imread(img_name).
This function is extremely slow for images with high resolution, I change this into w, h = imagesize.get(img_name).

**Comment by ForeverPs** [comment]
<img width="358" alt="image" src="https://github.com/RangiLyu/nanodet/assets/47919727/612c6ff6-6407-4dcd-a6fb-b9b08a2cc652">
pip3 install imagesize

**Comment by ForeverPs** [comment]
However, the code is stuck here:
<img width="581" alt="image" src="https://github.com/RangiLyu/nanodet/assets/47919727/6944957d-5101-44f0-8001-ba5be3cfdd8b">

**Comment by Sanath1998** [comment]
Hi @ForeverPs, 
Are u aware of how to save all the checkpoints of each epochs and what epochs does model.best.ckpt saves? Where to check those?

**Comment by Sanath1998** [comment]
And also i think in Nanodet training script we can't control. Is that what you have also experienced?
