### ISSUE TITLE
Is input image BGR format?

### ISSUE THREAD

**Issue by steven0129** [RangiLyu/nanodet#56]
想確認一下, 我觀察到讀取image的時候是使用cv2.imgread
想請問nanodet是train在input為BGR Format的image, 而非RGB Format的image上嗎?

https://github.com/RangiLyu/nanodet/blob/0edb0852c2131868e4183ae3fd5ae086a5cb3136/nanodet/data/dataset/coco.py#L104-L129

**Comment by RangiLyu** [comment]
是的，图片通道是BGR顺序

**Comment by steven0129** [comment]
了解了, 感謝

**Comment by steven0129** [comment]
了解了, 感謝
