### ISSUE TITLE
请问怎样可以将demo.py最终输出的bounding box输出？

### ISSUE THREAD

**Issue by ChenJiajun0011** [RangiLyu/nanodet#567]
运行demo.py后输出的bounding box是在哪里输出的呢？我看到visualize函数里面是画框，但是是把不同置信度的框画出来，没有看到哪里调用了NMS去输出最终的box啊，求教是在哪里输出的！球球了

**Comment by Sanath1998** [comment]
Hi @ChenJiajun0011,
NMS function is being called in  "def get_bboxes(self, cls_preds, reg_preds, img_metas)" api.
This can be seen inside **/nanodet/model/head/nanodet_plus_head.py** script.

**Comment by ChenJiajun0011** [comment]
> Hi @ChenJiajun0011, NMS function is being called in "def get_bboxes(self, cls_preds, reg_preds, img_metas)" api. This can be seen inside **/nanodet/model/head/nanodet_plus_head.py** script.

Okey got you, thanks!
