### ISSUE TITLE
关于项目部署的问题

### ISSUE THREAD

**Issue by busyyang** [RangiLyu/nanodet#59]
你好，我想请教两个问题：
1. 在`nanodet.cpp`文件中的` NanoDet::detect(cv::Mat image, float score_threshold, float nms_threshold)`函数中，给模型输入数据的时候是用的`ex.input("input.1", input);`,这里的input.1是什么意思呢，是输入层的名字吗，我怎么通过pytorch查看到这个名字呢，print(model)后没看到层的名字，在[Tencent/ncnn/tree/master/examples](https://github.com/Tencent/ncnn/tree/master/examples) 上看到基本上都是`ex.input("input", input);`，如果我加载自己训练的一个模型，这里应该怎么匹配？
2.  在`nadodet.h`中，有一个 std::vector<HeadInfo> heads_info，这个里面的值具体是什么含义呢，是和网络输出有关的吗

~~~cpp
    std::vector<HeadInfo> heads_info{
        // cls_pred|dis_pred|stride
            {"792", "795",    8},
            {"814", "817",   16},
            {"836", "839",   32},
    };
~~~

对pytorch以及nano网络都不是很熟，望见谅。

**Comment by leozicai** [comment]
input.1是输入层，我个人看模型结构的话是先将pth转为onnx然后用Netron看。
![22](https://user-images.githubusercontent.com/53112849/101120211-fe1efc00-3627-11eb-8d8f-779e074d4bb1.JPG)

**Comment by busyyang** [comment]
谢谢，下了Netron看，的确名字是input.1,那第二个问题`std::vector heads_info`是什么含义呢

**Comment by leozicai** [comment]
我也没玩过，懂的话我在上面就直接回答你了

**Comment by RangiLyu** [comment]
> 谢谢，下了Netron看，的确名字是input.1,那第二个问题`std::vector heads_info`是什么含义呢


是输出blob的name以及对应的stride，用netron打开.param看一下输出就知道了

**Comment by busyyang** [comment]
> > 谢谢，下了Netron看，的确名字是input.1,那第二个问题`std::vector heads_info`是什么含义呢
> 
> 是输出blob的name以及对应的stride，用netron打开.param看一下输出就知道了

输出节点明白了，我消化消化。`std::vector heads_info`的stride是怎么从Netron看出来的呢

**Comment by busyyang** [comment]
看到的输出节点是这样的，output的名字有了，stride没看到。

![image](https://user-images.githubusercontent.com/7272659/101129101-f1a49e80-363b-11eb-9e41-f75774dfbf7e.png)

**Comment by leozicai** [comment]
> 
> 
> 看到的输出节点是这样的，output的名字有了，stride没看到。
> 
> ![image](https://user-images.githubusercontent.com/7272659/101129101-f1a49e80-363b-11eb-9e41-f75774dfbf7e.png)

stride即下采样的步长
![Model_arch](https://user-images.githubusercontent.com/53112849/101131660-a214a180-3640-11eb-9ede-a5a810a2d1d8.png)

但是这个在网络中不是单纯的8,16,32来反映出来的，是经过多层的卷积，池化等，综合到一起形成。比如原图到8倍下采样是经过如下的结构：
![1](https://user-images.githubusercontent.com/53112849/101132262-a8574d80-3641-11eb-8e6c-961de9315aac.JPG)

**Comment by busyyang** [comment]
谢谢，打开简化的ONNX文件看到特征图尺寸了，理解了stride的大小。之前看.param文件，看不到特征图大小，所以疑惑了， 以为要一个一个数去......
