### ISSUE TITLE
Train images which contain no annotation

### ISSUE THREAD

**Issue by Wilfred-Yang** [RangiLyu/nanodet#63]
Hi, Thanks for your contribution. Except for images with annotations, I also want to train images with no annotation. Now I don't have any .xml file about images with no annotation. How should I do to train images with no annotations?

**Comment by leozicai** [comment]
maybe you can just use the empty xml as annotation(xml without object sections).

**Comment by Wilfred-Yang** [comment]
@leozicai thank you for your reply. I will try this

**Comment by Wilfred-Yang** [comment]
@leozicai thanks! it works in my case!

**Comment by leozicai** [comment]
You're welcome~

**Comment by deshpandeneeraj** [comment]
Could anyone help me with the same issue just with a coco dataset?
