### ISSUE TITLE
@RangiLyu,请问.pth转换成onnx后，如何直接使用onnx模型？采用opencv4.4加载会报错，请问还有其他方法吗？膜拜！！！

### ISSUE THREAD

**Issue by wpeak58** [RangiLyu/nanodet#64]

**Comment by leozicai** [comment]
onnxruntime应该可以

**Comment by XieRuicheng** [comment]
参考一下这个，用onnxruntime？
https://github.com/RangiLyu/nanodet/blob/47b1a7020898986d7e8f0e9464d9c711d969409f/demo_mnn/python/demo_mnn.py#L438-L455
