### ISSUE TITLE
导出的onnx文件时Sigmoid是在哪里插入的？

### ISSUE THREAD

**Issue by XieRuicheng** [RangiLyu/nanodet#67]
您好，我在使用 `export.py` 导出的onnx文件时，发现导出的onnx模型在输出分类score中包含了 Sigmoid算子，但是在pytorch模型中没有，请问导出onnx时的Sigmoid是在哪里插入的？

在 `export.py` 和 `demo.py` 中加在模型似乎并没有不同
https://github.com/RangiLyu/nanodet/blob/43a8a89005aa44fee9b338e607f7485a650023f4/tools/export.py#L8-L12
https://github.com/RangiLyu/nanodet/blob/43a8a89005aa44fee9b338e607f7485a650023f4/demo/demo.py#L26-L34

ONNX文件的末尾：
![image](https://user-images.githubusercontent.com/20857887/101596396-f13b4780-3a2f-11eb-8a01-d194629ccb7a.png)

**Comment by d246810g2000** [comment]
> 您好，我在使用 `export.py` 导出的onnx文件时，发现导出的onnx模型在输出分类score中包含了 Sigmoid算子，但是在pytorch模型中没有，请问导出onnx时的Sigmoid是在哪里插入的？
> 
> 在 `export.py` 和 `demo.py` 中加在模型似乎并没有不同
> https://github.com/RangiLyu/nanodet/blob/43a8a89005aa44fee9b338e607f7485a650023f4/tools/export.py#L8-L12
> 
> 
> https://github.com/RangiLyu/nanodet/blob/43a8a89005aa44fee9b338e607f7485a650023f4/demo/demo.py#L26-L34
> 
> ONNX文件的末尾：
> ![image](https://user-images.githubusercontent.com/20857887/101596396-f13b4780-3a2f-11eb-8a01-d194629ccb7a.png)

sigmoid 和 transpose 都是在後處理的地方加上去的
https://github.com/RangiLyu/nanodet/blob/main/nanodet/model/head/gfl_head.py#L400

**Comment by RangiLyu** [comment]
在这里加入的
https://github.com/RangiLyu/nanodet/blob/43a8a89005aa44fee9b338e607f7485a650023f4/nanodet/model/head/nanodet_head.py#L125
