### ISSUE TITLE
Finetuning from a pretrained model

### ISSUE THREAD

**Issue by abdelrahman-gaber** [RangiLyu/nanodet#75]
Is there a way to use the coco pretrained model as intialization to fine-tune with my custom dataset? 
I can see the flags in the yaml file to resume training, but nothing for using pretrained weights with different dataset!

```yaml
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
```

**Comment by RangiLyu** [comment]
Just change load_model to Coco pre-train model path, then it will load pre-train weight before training.

**Comment by abdelrahman-gaber** [comment]
Thank you so much. It is working now. 
The mistake I did was setting `resume: true` so it was showing errors.

**Comment by wwdok** [comment]
The `resume:` and `load_model:` have same indent or `load_model:` has double indents while `resume:` has single indent ?
