### ISSUE TITLE
模型大小

### ISSUE THREAD

**Issue by ljiqy** [RangiLyu/nanodet#79]
训练出来的模型7.2M，我看介绍说模型1.8M，请问转ncnn时是进行了模型的量化操作么？

**Comment by RangiLyu** [comment]
7.2m是pytorch的checkpoint，里面包含了优化器。
导出onnx后是3.8m，是32位模型的大小。
最后转ncnn使用ncnnoptimize进行fp16存储，得到1.8mb的模型。
