### ISSUE TITLE
About inference time on kirin 980 CPU

### ISSUE THREAD

**Issue by holyhao** [RangiLyu/nanodet#81]
Thansk for your work. I implement the demo_android_ncnn on my mate20(kirin 980) and do not change any thing. The inference time is about 30ms, as about 30FPS，which is different from your report.  So, how can I  get the right inference time as your report. Looking forward to your reply.

**Comment by hive-cas** [comment]
我遇到了同样的问题，在titan V GPU上速度大概50fps左右，按说如果在cpu跑97fps，那在GPU上得上200fps吧，是不是解码的时间也算进去了？贴图：
forward time: 0.019s | decode time: 0.008s | viz time: 0.002s
forward time: 0.021s | decode time: 0.011s | viz time: 0.004s
forward time: 0.018s | decode time: 0.009s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.021s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.020s | decode time: 0.008s | viz time: 0.002s
forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.021s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.009s | viz time: 0.003s
forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
forward time: 0.017s | decode time: 0.007s | viz time: 0.001s

**Comment by RangiLyu** [comment]
> Thansk for your work. I implement the demo_android_ncnn on my mate20(kirin 980) and do not change any thing. The inference time is about 30ms, as about 30FPS，which is different from your report.  So, how can I  get the right inference time as your report. Looking forward to you

 Inference latency is tested with ncnn-android-benchmark from this repo  https://github.com/nihui/ncnn-android-benchmark

The latency in Android camera demo containing image preprocessing, postprocessing and bbox visualization. So the time cost is longer in camera demo.

**Comment by RangiLyu** [comment]
> 我遇到了同样的问题，在titan V GPU上速度大概50fps左右，按说如果在cpu跑97fps，那在GPU上得上200fps吧，是不是解码的时间也算进去了？贴图：
> forward time: 0.019s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.021s | decode time: 0.011s | viz time: 0.004s
> forward time: 0.018s | decode time: 0.009s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.021s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.020s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.021s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.009s | viz time: 0.003s
> forward time: 0.017s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.018s | decode time: 0.008s | viz time: 0.002s
> forward time: 0.017s | decode time: 0.007s | viz time: 0.001s
> 
> 为了确认是否在GPU上直接跑的，我看有这么句话：predictor = Predictor(cfg, args.model, logger, device='cuda:0')，应该是用的GPU跑的。

pytorch不是推理专用的库，inference的过程没有经过优化，使用ncnn进行bn融合以及fp16量化，以及对后处理优化后才能在arm CPU上得到readme中的速度。如果要在pc端GPU测试推理速度，建议使用demo_ncnn中的代码进行测试。使用vulkan加速后1060上每帧大约5ms，在3090上约3~2ms，达到200fps是肯定没问题的。

**Comment by hive-cas** [comment]
> pytorch不是推理专用的库，inference的过程没有经过优化，使用ncnn进行bn融合以及fp16量化，以及对后处理优化后才能在arm CPU上得到readme中的速度。如果要在pc端GPU测试推理速度，建议使用demo_ncnn中的代码进行测试。使用vulkan加速后1060上每帧大约5ms，在3090上约3~2ms，达到200fps是肯定没问题的。

非常感谢您回复！这么好的project真是难得！
我明白您的意思，不过我十分惭愧不会用C++开发，只会python，所以NCNN那个demo对我来说难度太大，如果想用ncnn的话，是否可以通过pytorch--》ONNX--》NCNN这样获得加速？效果是否也会达到10ms左右？
