### ISSUE TITLE
Training error with my own VOC dataset

### ISSUE THREAD

**Issue by Billy1203** [RangiLyu/nanodet#87]
在Start warm up就卡住了后面就没有反应了，有遇到类似的问题吗？
我用一个公开数据集可以运行出模型，但是卡住了不知道是我自己的数据有问题还是代码中有什么地方要修改

**Comment by RangiLyu** [comment]
请提供一下系统和运行环境

**Comment by Billy1203** [comment]
> 请提供一下系统和运行环境

hardware: nvidia 1080ti, i7-6900k
software: ubuntu18.04, cuda 10.2, pytorch 1.7.1, torchvision 0.8.2, opencv-python 4.4.0.46
I can run demo.py with your models.

**Comment by Billy1203** [comment]
I got it. My training_image dataset is too small, I should change batchsize_per_gpu.
