### ISSUE TITLE
Question : What is the full name of abbreviation `mlvl` in `mlvl_bboxes` and `mlvl_scores` ?

### ISSUE THREAD

**Issue by wwdok** [RangiLyu/nanodet#88]
I am just curious about it, and maybe knowing that can help me understanding the code ... ~

**Comment by RangiLyu** [comment]
`lvl` means level. `mlvl_bboxes` means  boxes from all FPN levels.

**Comment by wwdok** [comment]
Got it ! Thank you very much !
