### ISSUE TITLE
Some bugs found when building `demo_ncnn` on MacOS

### ISSUE THREAD

**Issue by ZhangAoCanada** [RangiLyu/nanodet#90]
**Bugs:**

1. A typo in `${project_dir}/demo_ncnn/nanodet.h` on line 7. It should probably be `NANODET_H` instead of `NAMODET_H`.
<img width="411" alt="Screen Shot 2020-12-18 at 2 28 57 PM" src="https://user-images.githubusercontent.com/43648733/102653827-8aa7df00-413d-11eb-8ae2-cf636399594e.png">

2. In `${project_dir}/demo_ncnn/main.cpp` line 237, in order for MacOS to complie the cpp file, I changed `img_name` to `img_name.c_str()`. I don't know if it is because of the different compliers yet (clang++ vs g++),  but I may have to compile on Linux in the future to see the difference.
<img width="520" alt="Screen Shot 2020-12-18 at 2 32 21 PM" src="https://user-images.githubusercontent.com/43648733/102654082-f4c08400-413d-11eb-9682-8a3fbb66d12b.png">

**Some suggestions:**

1. Pretty nice work done there and the performance is amazing. Thanks for your work. Just a little suggestion for `pytorch` users. So probably there are ppl like me want to inference the model on CPU only, but the inference_demo in the current repo is targeted GPU only. I had to turn off some settings in order to make it run.

2. About `demo_ncnn`, nicely done! Uhhh, could you make the `CMakeLists.txt` more compatible with MacOS? like the ncnn libs are named `*.lib` in Linux but `lib*.a` in MacOS. :P

**Comment by RangiLyu** [comment]
Thank you very much for your comments and suggestions! I'll improve the pytorch demo and  cmakelists in ncnn demo later.

**Comment by RangiLyu** [comment]
Simplify CMakeLists in commit 57e4aa7d7b7468aab73ab0a8cbe48134fc8470bd
