### ISSUE TITLE
关于MNN1.1.0版本问题

### ISSUE THREAD

**Issue by tunmx** [RangiLyu/nanodet#92]
请问是否有检查过在mnn 1.1.0版本下存在的问题，我在1.1.0版本下使用仓库内的mnn模型推理出来的结果会有问题，然后用1.1.0的转换器通过onnx转出的mnn模型也会有一样的问题

**Comment by RangiLyu** [comment]
@XieRuicheng

**Comment by XieRuicheng** [comment]
请使用 `MNN 1.0.0`，`MNN 1.1.0` 下很多从ONNX转的检测模型的结果都对不上

**Comment by XieRuicheng** [comment]
C++ 测试了刚刚发布的 `MNN 1.1.2` 版本, 检测结果看起来基本正常，但是目标的得分和Pytorch还是有区别。`MNN 1.0.0` 的得分和Pytorch小数点后四位是完全一致的。

Python 版本在pip任然是 Dec 22, 2020 的 release，此前测试有问题，这次没有测试。

**Comment by eeric** [comment]
test myself,
nanodet model convert to MNN one by 1.0.0, not use 1.1.0 or 1.1.2
notice: model converted by MNN-1.0.0 that was use to vs2017 demo_mnn with MNN-1.1.2 library

**Comment by scutzhe** [comment]
mnn version 1.0.0 is OK、

**Comment by job2003** [comment]
> 请使用 `MNN 1.0.0`，`MNN 1.1.0` 下很多从ONNX转的检测模型的结果都对不上

如何安装python版本的1.0.0，我使用
pip install MNN默认安装1.1.0版本。
如果使用pip install MNN==1.0.0会出现错误。
_ERROR: Could not find a version that satisfies the requirement MNN==1.0.0 (from versions: 1.0.5, 1.0.6, 1.1.0)
ERROR: No matching distribution found for MNN==1.0.0_

**Comment by XieRuicheng** [comment]
> 如何安装python版本的1.0.0，我使用
> pip install MNN默认安装1.1.0版本。
> 如果使用pip install MNN==1.0.0会出现错误。
> _ERROR: Could not find a version that satisfies the requirement MNN==1.0.0 (from versions: 1.0.5, 1.0.6, 1.1.0) ERROR: No matching distribution found for MNN==1.0.0_

目前 [pypi](https://pypi.org/project/MNN/1.0.0/#files) 上只有py27，py35-py37的版本，其他python版本需要自己编译。

另，刚刚测试了 MNN 1.0.6，检测结果正确

**Comment by ling9601** [comment]
利用仓库里提供的[nanodet-320.mnn.](https://drive.google.com/drive/folders/1dEdAXkof_lCusYBNrgbGzdLFZbDPMiFn?usp=sharing)， 在 MNN 1.0.0 与 1.1.3 上的检测结果一致(两个版本都在树莓派上编译的)

**Comment by scutzhe** [comment]
> mnn version 1.0.0 is OK、

but backbone is ghostNet，mnn version 1.0.0 error, mnn version 1.1.0 error too

**Comment by scutzhe** [comment]
> > mnn version 1.0.0 is OK、
> 
> but backbone is ghostNet，mnn version 1.0.0 error, mnn version 1.1.0 error too

open /tools/converter/source/onnx/Clip.cpp and comment out two lines with DCHECK_EQ.  
Then rebuild and it works well
