### ISSUE TITLE
能不能加个数据增强的步鄹，或者在哪里可以加

### ISSUE THREAD

**Issue by liuzimo** [RangiLyu/nanodet#95]

**Comment by RangiLyu** [comment]
数据预处理的Pipeline中已经实现了perspective, scale, stretch, rotation, shear, translate, flip, brightness, contrast, saturation这几种数据增强，如果想要增加其他的增强方式，可以在nanodet/data/transform中增加，并包含进
https://github.com/RangiLyu/nanodet/blob/2a146a8821fbed1fbf02a49d318f55bc6d8ef718/nanodet/data/transform/pipeline.py#L16

**Comment by Senwang98** [comment]
@RangiLyu 
你好，去请教一下如果我要在mmdet2上面对齐nanodet的精度，数据增强部分是不是就是RandomAffine、flip、resize、PhotoMetricDistortion、Normalize这几个部分就可以跟你的数据增强对齐了？
