### ISSUE TITLE
how to train model with cpu device

### ISSUE THREAD

**Issue by sotaDetector** [RangiLyu/nanodet#96]
it reports "AssertionError: Torch not compiled with CUDA enabled" when i train the model with my cpu device

**Comment by RangiLyu** [comment]
Sorry, cpu training is currently not in the support list. 
You may try to replace all CUDA related codes to CPU.

**Comment by JefferyChiang** [comment]
I change gpus to 0 from train.py and it work for training with my I5 CPU.
The workers_per_gpu and batchsize_per_gpu in .yml config will map to CPU relatively.
`    trainer = pl.Trainer(
        default_root_dir=cfg.save_dir,
        max_epochs=cfg.schedule.total_epochs,
        gpus=0, #cfg.device.gpu_ids  #0 for CPU
        check_val_every_n_epoch=cfg.schedule.val_intervals,
        accelerator=accelerator,
        log_every_n_steps=cfg.log.interval,
        num_sanity_val_steps=0,
        resume_from_checkpoint=model_resume_path,
        callbacks=[ProgressBar(refresh_rate=0)],  # disable tqdm bar
        logger=logger,
        benchmark=True,
        gradient_clip_val=cfg.get("grad_clip", 0.0),
    )`

**Comment by Sidd1609** [comment]
@JefferyChiang  and @RangiLyu is it possible to run an evaluation on the COCO dataset using the pre-trained weights on a CPU device
