### ISSUE TITLE
讨论下，gfl的类别置信度联合表达和IOU强相关，这样会带来很高的误报率吧

### ISSUE THREAD

**Issue by connorchen** [RangiLyu/nanodet#97]
FCOS虽然是两个分支，但是各自的含义都很清楚，一个负责预测类别，一个负责预测置信度，gfl中的联合表达和IOU相关，如果有一个类别的box回归的不好，那置信度学习的区间就偏低，那不是很容易和背景的得分混在一起？
我自己训练的话目前就有这个问题，虽然AP很高，但是误报率也高的离谱

**Comment by RangiLyu** [comment]
可以把gfl替换成focal loss做一下对比实验，看看是否是由于使用IOU作为得分标签导致的误报

**Comment by connorchen** [comment]
好的，多谢

**Comment by LiuYuZzz** [comment]
> FCOS虽然是两个分支，但是各自的含义都很清楚，一个负责预测类别，一个负责预测置信度，gfl中的联合表达和IOU相关，如果有一个类别的box回归的不好，那置信度学习的区间就偏低，那不是很容易和背景的得分混在一起？
> 我自己训练的话目前就有这个问题，虽然AP很高，但是误报率也高的离谱

改成focal loss后，实际效果有提升吗？
