### ISSUE TITLE
安卓MNN尝试移植，检测结果有问题

### ISSUE THREAD

**Issue by cmdbug** [RangiLyu/nanodet#98]
在使用demo的mnn代码移植到安卓后，检测结果满屏都是框，模型直接下载网盘的，代码使用demo提供的，除了必要的修改部分，其它的没有动。请问大佬可能是什么原因？
![image](https://user-images.githubusercontent.com/19603468/103198537-83de5080-4923-11eb-8d8b-d776bbdb76e6.png)

**Comment by cmdbug** [comment]
MNN版本bug，使用旧版本解决了。

**Comment by cmdbug** [comment]
1.1.0版本有bug

**Comment by eeric** [comment]
test myself,
nanodet model convert to MNN one by 1.0.0, not use 1.1.0 or 1.1.2
notice: model converted by MNN-1.0.0 that was use to vs2017 demo_mnn with MNN-1.1.2 library
