### ISSUE TITLE
在您的基础上，尝试加入了特征点回归，效果如下。

### ISSUE THREAD

**Issue by jiangtaoo2333** [RangiLyu/nanodet#99]

**Comment by jiangtaoo2333** [comment]
![img_0_res](https://user-images.githubusercontent.com/31915238/103255010-9d82a500-49c2-11eb-9cd1-4d80b5f21705.jpg)
![img_1_res](https://user-images.githubusercontent.com/31915238/103255012-9f4c6880-49c2-11eb-95b4-bc781b8060a0.jpg)
![img_2_res](https://user-images.githubusercontent.com/31915238/103255013-a1162c00-49c2-11eb-876e-3dbe1471da1a.jpg)
![img_3_res](https://user-images.githubusercontent.com/31915238/103255014-a1aec280-49c2-11eb-940c-458a73266ced.jpg)
![img_4_res](https://user-images.githubusercontent.com/31915238/103255015-a2dfef80-49c2-11eb-9c18-11e275ac487a.jpg)

人脸对齐，对尺度更加敏感；不想检测那样在不同大小，都能较好的检测出来。我的想法是，既然检测能检测好，对齐质量也不至于这么低，请问您有什么改善的建议么。谢谢您的开源代码。

**Comment by RangiLyu** [comment]
试试在数据增强的时候引入更多缩小的训练样本

**Comment by sunjunlishi** [comment]
@jiangtaoo2333 你好，特征点回归，你是怎么做的，怎么更改训练代码，能够支持特征点回归
